### ISSUE TITLE
styles for images in articles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#111]
we now have some example images to test with when implementing these. note that the styles include diff. versions for wide/tall images and we also want to use hugo's image resizing capabilities.

# testing

the [data beyond vision essay](https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/) now has several images to test with, including:
- the concept map, which is a landscape (wide) image
- the photo of the loom, which is a portrait (tall) image
- an svg image (in this case, an icon) added after the loom photo (it has a caption "SVG image for testing").

we want to check the image sizing across browsers and definitely on mobile devices, since margins change depending on the screen size. ideally images should never look blurry/pixelated, and they should never be taking a noticeably long time to load.

**Comment by thatbudakguy** [comment]
@gissoo this is ready for a look; I added testing notes. let me know if the sizing/margins for images across devices is what you had intended. @rlskoeser noted that the tall/"portrait" image (in this case the one of the loom) is really large, especially on desktop (you need to scroll to see all of it). what do you think about this?

**Comment by gissoo** [comment]
@thatbudakguy Thank you, Nick!! I tested the two images and the icon on desktop and mobile Safari, Chrome, and FF. 

- They all look fine! I agree with @rlskoeser that portrait images on desktop is really large – I made the images on desktop, both portrait and landscape match the approach for the other two devices, i.e. they align with the width of the paragraph now. I think that might be a better approach.

- You followed the image styles for the icon as well, correct? I don't recall having an icon styleguide for the article and can't find any in Figma right now (just checking to make sure) – as far as I can tell the icon is following the image styles. 

- The first image/concept map is pixelated – is it because of the quality of the image itself? 
Note: I wish we could have a zoom feature for some of the images such as the concept map, it's too detailed and would benefit from being zoomable, it will be nice certainly for mobile.

**Comment by thatbudakguy** [comment]
I need to revise images sizes on desktop (see [slack conversation](https://cdhprinceton.slack.com/archives/CR6JCFQHE/p1599763953022000)):
- [ ] landscape mode images now match the width of paragraphs
- [ ] portrait mode images have the same ratio to the paragraph width as they do on mobile/tablet

**Comment by gissoo** [comment]
@thatbudakguy thank you! I just tested on desktop and mobile FF, chrome, and safari. These look great. Although for some reason I had made the portrait images on desktop even smaller, I just revised them in the design – @rlskoeser do the portrait images look ok to you on desktop now? 

- Also, @thatbudakguy I am noticing that on mobile (320px), the portrait image of "setting up the warp on the loom to start weaving" is only 217.5px wide, according to the designs the minimum is 250px – can we fix this? I didn't notice this last time at all, it didn't seem to be happening.

@thatbudakguy could you also respond to my two questions in my comment above? (the 2nd and 3rd bullets)

**Comment by thatbudakguy** [comment]
documenting decisions from slack:

- **svg** images (sometimes icons, sometimes charts/other figures) will respect their _intrinsic size_ if they're smaller than the paragraph width (e.g. for icons), but otherwise will fit the paragraph width like a landscape image (e.g. for charts). we will provide guidelines for minimum intrinsic size and maximum file size (and potentially also a recommended intrinsic size).
- **landscape** images (non-svg) always fit the width of the paragraph, and have a max-height restriction so that they can't be too tall to read their caption (should rarely if ever happen, but just in case)
- **portrait** images (non-svg) have a min-width of 250px and otherwise are about ~75% of the paragraph width, and have a max-height restriction so that they can't be too tall to read their caption

**Comment by thatbudakguy** [comment]
ok, this is ready for (hopefully final!) review. I created a new [testing "essay"](https://startwords.cdh.princeton.edu/issues/1/image-format-testing/) that has some examples of images embedded in it; the captions describe how the images should display in each case.

**Comment by gissoo** [comment]
@thatbudakguy Thank you!!!
There are two issues: 
1. For some reason I still see the 2nd image on the page (the portrait one) is still showing me is 217.5px instead of 225px on mobile and also the first image of the concept map is 290px instead of 300 - think this matters – do you know if what I'm seeing is wrong? Or what is happening? (this doesn't matter as much but just to note: I continued to inspect that saw that on the 1024 screen the paragraphs and the first landscape image are 592px instead of 596px) 

- ok I hope you see my question this time, please let me know, I asked earlier too: The first image/concept map is pixelated as I shrink the desktop browser and looks more pixelated on mobile than when on a larger desktop – do you know why this is happening? And how we can solve?

**Comment by rlskoeser** [comment]
@gissoo on the concept map — not sure why it's pixelated (probably because it's text), but we're going to solve this by switching to an SVG instead of the PNG we're using right now.

**Comment by thatbudakguy** [comment]
@gissoo about the pixelation - I think it might actually be the same issue as the concept map not being full-width, since something is going wrong on Safari and the image isn't being resized correctly. I can't replicate this issue using Safari 14.0 on my MacBook (1440px screen); the image always displays at the paragraph width and isn't pixelated. Could you check your Safari version? @rlskoeser do you see this as well?

about the slight (a few px) sizing differences - it turns out this is because I had the margins wrong! the correct margin for the body text on mobile is 10px on each side, but I had 15px, which made the text be 290px wide instead of 300px - thus, the portrait image was 75% of 290px, which is 217.5px. I've corrected it now - let me know if you see the correct image sizes.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy thank you for writing!! 
- regarding the image width on Safari – it's now fixed somehow! my Safari is still old, but this issue is not happening anymore. 
- regarding the pixelation, this is happening on all browsers. I have provided a SVG version of the concept map in the "production asset" folder in the drive fwiw to potentially help with this.
- thank you, @thatbudakguy the margins look great now!!

Shall I close this issue? Or should it be open to track the concept map issue, or should this be tracked else where?

**Comment by thatbudakguy** [comment]
i've switched the essay to use the SVG version of the concept map instead. if it looks right to you, go ahead and close this.

**Comment by gissoo** [comment]
@thatbudakguy it's still so pixelated on all my browsers!! I wonder why, this is not supposed to happen with svgs.

**Comment by gissoo** [comment]
@thatbudakguy Ok so on Slack we conversed about this and I found out I should have been looking at the dbv essay page and not the image format testing page to see the svg concept map. I looked at it and it was not pixelated however it's very small and hard to read on desktop since zooming in is not very easy on desktop – I have revised the concept map so that it's narrower (shortened the curved arrows) to help it appear larger, it's helped a bit. I'll leave it for now. 
I think this does deserve a zoom feature in the future, just like one that we implemented for S&Co cards, it would improve the experience a lot.
