### ISSUE TITLE
As a reader, I want to read a long piece.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#12]
what this issue covers:
- all information in the header of an article (issue number, theme, authors, DOI, etc) and its design
- all of the body text of the article as well as headings (font size, line height, etc)

what this issue doesn't cover/isn't tested here:
- contextual notes/endnotes
- embedded viewers or content
- pull quotes
- specially styled sections like the purple sections in the DBV essay

**Comment by rlskoeser** [comment]
"long pieces" or feature articles are set up with content type article. Layouts for individual article view are in the startwords theme under layouts/article. 

Because we decided on the simplest directory structure that would give us the URLs we want, articles should be placed in an issue number directory and have the type:article specified in the page metadata.

**Comment by thatbudakguy** [comment]
ok, this is ready for @gissoo's review, finally! might not need @gwijthoff's :eyes: but a quick double-check couldn't hurt. see the issue description for what is covered by this issue.

**Comment by gissoo** [comment]
@thatbudakguy 
This looks great, a couple of points:
- on FF, Chrome, and Safari iOS and shrunk desktop (to mobile and tablet sizes), the entire header section is in the wrong column – it should be shifted to the right by one column (The designs do this for mobile and tablet – also on tablet in order to keep mobile and tablet as uniform and consistent as possible just like how their font sizes are the same) – however I think this is crucial for mobile because the nav on the top left is covering the header section, it's important that this doesn't happen. 

- with the authors, space is needed after each comma. 

- Regarding the "line-height" that you are referring to, I had mentioned changing the "paragraph spacing", are we talking about the same thing? I **don't** mean the "leading" which is the term used in design – I think what I mean in css was called "margin-bottom". Just to make sure we are on the same page. If you have already changed the paragraph spacing, I agree it's not enough, maybe 2 more px? 
The leading was okay and doesn't need revision. 

- I'm assuming this issue also does not consist of the styling of the section headers, for instance, "Stacking New and Continuing Membership Activities of Shakespeare and Company Library", correct? Because they are supposed to be much narrower and not full width.

**Comment by gwijthoff** [comment]
Came here to mention the need for a space after commas between author names.

Also, it looks like @gissoo's [Figma designs](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=190%3A159) have the TXT and PDF links in a slightly heavier font weight, which I like.

**Comment by thatbudakguy** [comment]
> the entire header section is in the wrong column

good catch; I've updated it to match the designs.

> with the authors, space is needed after each comma.

I can't reproduce the lack of spacing in any browser, including with the safari device emulator...maybe it's a mysterious mobile safari bug? I tried adding a space anyway, but have no idea what will happen. let me know if it's resolved!

> Regarding the "line-height" that you are referring to, I had mentioned changing the "paragraph spacing", are we talking about the same thing? I don't mean the "leading" which is the term used in design – I think what I mean in css was called "margin-bottom". 

Thanks for explaining, totally get it now. I adjusted the margins by 5px.

> I'm assuming this issue also does not consist of the styling of the section headers

Right - they have a special style for the dbv essay, so that's tracked on #88. And Rebecca's essay doesn't really have headings (I think), so we don't really have a way to test what a "regular heading" looks like...but how they look now is what that would be.

> the TXT and PDF links in a slightly heavier font weight

good catch @gwijthoff! I bumped it up to `400`.

**Comment by gissoo** [comment]
- @thatbudakguy thank you so much!! @gwijthoff thanks for catching!!
- Everything looks much better! The comma problem is fixed everywhere now! I think it was happening on all browsers before. 
- @thatbudakguy  would you please add 2 more px to the margin-bottom? Looking at RM's article, it still is a little tight. 
- This is interesting, not feeling strongly about it, but just to note, there is extra space happening here even though it's the same paragraph. I suspect the reason is the note reference number, but it's much more noticeable on mobile than it is on desktop. ![Image from iOS (8).jpg](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/8a38acea-ff78-47e2-9fe6-04bd493bbad8)

**Comment by rlskoeser** [comment]
@gissoo I also noticed that problem with the footnote references. We had a similar issue on S&co, I think I resolved it by making the superscript font smaller. I think the options are to either make the font smaller or to adjust the alignment so it isn't so high above the text.

**Comment by thatbudakguy** [comment]
@gissoo I've increased the paragraph spacing by 2px and it looks like @rlskoeser added the fix for the superscript numbers. let me know if you think this is ready to close.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser  Thank you so much!! This looks great!! You're both amazing :)
