### ISSUE TITLE
As an editor, I want to associate articles with their generated PDFs.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#131]
@thatbudakguy would you make an issue for the PDF solution we need for issue 1 ? Articles should have an optional pdf url metadata field (maybe just `pdf` ?), and it should render similarly to the TXT link per the design when it's set.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/startwords/issues/6#issuecomment-698587697_

**Comment by thatbudakguy** [comment]
@rlskoeser hope I'm not missing anything and this is as easy as adding a `pdf` property to an article and then handling it in the template. I also added `type=` properties to both format links to hint the mime type to the browser, since that's [supported for `rel=alternate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) (I didn't see `rel=alt` btw, so I changed it to `alternate`).

I added a pdf link to the data beyond vision essay so it can be tested, lmk if you think it's OK to close this.

**Comment by rlskoeser** [comment]
@thatbudakguy these changes look good. Thanks for catching the alt/alternate.

There's a related change we need that I forgot about: there's a commented out placeholder for `citation_pdf_url` in the head metadata, it should be populated when we have one. 

TXT and PDF links are supposed suppressed for PDF, so print css needs to be revised for the alt/alternate change, since the rule is currently keyed on `a[rel=alt]`.

I'll go ahead and make those changes, but thought you should be aware.

**Comment by rlskoeser** [comment]
@thatbudakguy ok with me to close once you review my commits ⬆️

**Comment by thatbudakguy** [comment]
changes look good; thanks for handling it & letting me know!
