### ISSUE TITLE
As a reader, I want to preview the long pieces in an issue.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#16]
# dev notes
this corresponds to the article summary template in Hugo. it shows the first few words of an article's text along with its title (as a link) and the list of authors. it is visible on both the homepage and the single issue page.

**Comment by rlskoeser** [comment]
Like articles, issues are also implemented as a custom Hugo content type. There are custom list and single layout templates in our startwords theme under issue.

To get the urls we wanted, issues should be created as the `_index` file within the folder for that issue (see `issues/1` in the current version of the site). Because it's an index page, we have to specify type:issue and layout:single in the page metadata.

Issue template isn't currently displaying the opening paragraphs of the articles, but the logic to do it has been implemented on the home page template (layouts/index.html in the startwords theme) and should be easy to adapt (or, better yet, reuse if it is similar enough on the two pages).

**Comment by thatbudakguy** [comment]
this is subsumed by the homepage / single issue page github issues, so no longer required.
