### ISSUE TITLE
Adjust vertical spacing between the three featured essays on the homepage and the single issue page

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#225]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff [here is what I have got on Figma](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3002%3A9092)

I'm proposing that each essay would be aligned with the last line of the essay title that comes before it. I had other ideas at first but this approach would make the page look more balanced. It would be great if we can test this proposal with the actual content to see if any problems occur with text running into each other from opposite sides.

**Comment by rlskoeser** [comment]
Documenting from conversation with @gwijthoff :

- this looks great on figma, but we're not sure how well it will work with actual content
- not sure if it is technically possible to align with the last line of the title before (since we don't know how the browser will wrap the text)
- we'll keep this design as the ideal; wait to modify the layout until we have finalized first lines (Grant will work with the authors on that), and then fine-tune the layout to get as close as we can to this

closing this issue since we're happy with the design
