### ISSUE TITLE
Design a way to switch the language displayed in the main nav sections of the website

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#228]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff what is the goal of displaying the nav and the about page in Spanish for this issue? Is it so that readers who do not read English can understand what Startwords is and learn more about it?

**Comment by rlskoeser** [comment]
Sorry I never replied! This is because I think it would feel like a cop-out to display the essay in Spanish and not localize anything else about the site. 

It might be mitigated by your suggestion of displaying the Spanish version of the essay by default (which I think makes it clearer that it's the primary version)
