### ISSUE TITLE
Revise the alignment and placement of the opening line shadow text

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#254]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff I have proposed a variety of text shadows. Please take a look and tell me if you have suggestions on which ones to omit or pursue. [here they are on Figma](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3399%3A18404), I'll scale and place on mobile once we eliminate some, having a hard time deciding.

**Comment by rlskoeser** [comment]
@gissoo exciting!

I think the overlapping layers with same size and opacity are impossible to read and end up looking jumbled, I would eliminate those. 

I like the different size and opacity a lot. 

The gradient versions are interesting, but I'm not sure if I like them are not; they would be more difficult to implement, which worries me at this point. I don't think I can apply a gradient to a text shadow, which was how I was planning to implement the secondary version of the background text.

**Comment by gwijthoff** [comment]
I was initially drawn the most to option 4: same size, different opacities, linear gradient, because the shadow text draws back / recedes as the eye approaches the main text, allowing it to stand out more. Looks cool. But if @rlskoeser thinks it will be difficult to implement, it's certainly not necessary.

Option 2 isn't my favorite from an aesthetic perspective, but I don't really have a justification for that feeling. It reminds me of [some](https://www.rollingstone.com/wp-content/uploads/2018/06/rs-135961-c35c162ca72880319af7bab1af2799a69bba9ec1.jpg?w=500) [1990s](https://www.rollingstone.com/wp-content/uploads/2018/06/rs-135993-613a07c24562e22d58e50c28f74fd48789bd0b2e.jpg?w=500) [album](https://i.discogs.com/bcXYLxZM8YgmojiicDRhr1DW3_MSwMXIMpz81w7JWwU/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4OTUz/MDMtMTMwNjEyOTk2/MS5qcGVn.jpeg) [covers](https://1.bp.blogspot.com/-U564NwT90WE/TjQCdoUXJHI/AAAAAAAACxs/MgSkvLK8LEg/s1600/2.jpeg), but I guess the 90s are back now, right?

Maybe a new option "3.5" could be a happy medium? Same size, different opacities, no gradient?

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff thanks for writing, all makes sense. [here is version 3.5 (same size, different opacities, no gradient)](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3426%3A9912). Grant, the reason I didn't offer the 3.5 is that without the gradient you can see the lighter shadow starts in the middle of the page and to me that looks a bit horrible, I don't think we should display that. 
I'd like it to always to be a bit more "immersive" and to either not able to tell where something started/ended or just always be on the edge while preferably go over/under/overlap with the actual content that's 100% visible. 

Could we go with [3.6](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3426%3A10442)? It won't be overlapping with the main content though, kind of boring but I prefer it to 3.5. (don't like it as much as 2 and 3 though, but it's ok.)

**Comment by gwijthoff** [comment]
@gissoo thanks for sketching these extra options -- it's much easier to visualize their pros and cons now! If you think option 3 would work without a gradient, let's go that direction since you're more excited about it. I can see how having shadow text behind the main body text would make things more immersive and interesting, definitely. As long as it doesn't interfere with readability, I see where you're coming from.

**Comment by gissoo** [comment]
@gwijthoff Option 3 without the gradient is 3.5 – I think it won't work without the gradient, it's the "a bit horrible" case I mentioned :D

**Comment by gwijthoff** [comment]
@gissoo 🤦 sorry, I meant option 2. Despite my 90s comment. If you think it's the most interesting among the options we haven't eliminated for readability reasons, then let's go for it.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff thanks for your comments. I've picked option 2 and applied it on mobile as well – please read the text for implementation on the left of the designs and let me know if they don't make sense for implementation I can resolve or reframe. 

[Here are the designs ](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3399%3A18602)

**Comment by gwijthoff** [comment]
Looks awesome, thanks @gissoo! Can't wait to see it on the site.
