### ISSUE TITLE
Revise the language toggles so they're visually correct 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#262]
@rlskoeser @gwijthoff  I finally revised the toggles last week. I think the angles are better now. Let me know what you think, [they're on Figma](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3102%3A9793)

Feel free to [look at the site pages here so you can see what it looks like in context
](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3009%3A9675)

I've kept the "old version" so you can compare them "side by side".

**Comment by rlskoeser** [comment]
@gissoo I think the new version will be harder for me to generate in pure 3D css (partly because I'm cheating and my cube only has three faces, but also because I'm not sure what angle will show you three faces if this is a cube). 

However, the revised toggles look more like keyboard buttons, which I kind of like. If @gwijthoff  is happy with these, then would you export a background image for the button in the "up" state? That should be easy to use.  (This would be simplest)

If you want to keep it as 3D cube, then could we experiment a little with this 3D cube generator to generate the perspective you want? https://www.cssportal.com/css-3d-transform-generator/

**Comment by gwijthoff** [comment]
Uh, yea I'm happy with these! I really like the "keyboard" style buttons @gissoo. No preference on whether we keep the 3d cube or use a background image.

**Comment by gissoo** [comment]
@rlskoeser I'll export the image now – should I upload on github?

**Comment by rlskoeser** [comment]
@gissoo I'm not sure where I want it yet! Could you export and send to me and I'll upload with a co-author commit?
