### ISSUE TITLE
As a reader, I want to save an article using the Zotero citation manager.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#29]
## testing notes
Go to the test articles on the test site and try harvesting with Zotero. Check that the metadata in Zotero is complete and matches the values you see on the page.

----

moved from https://github.com/Princeton-CDH/startwords/issues/7#issue-562723053

**Comment by rlskoeser** [comment]
I remembered when Grant and I were reserving DOIs, I think Zotero can harvest metadata from DOIs linked on a page — so maybe we get this for free, by virtue of using DOIs.  I think DOI metadata is going to be much better than COINs .

Anyone want to test this to confirm?

**Comment by rlskoeser** [comment]
I did some tests, and it doesn't seem like Zotero can reliably harvest the DOI. What's more, on the DBV piece it's picking up metadata from Sketchfab instead and that seems to supersede other things on the page.

I think it's better to go with something we know Zotero will be able to detect and handle.

**Comment by thatbudakguy** [comment]
whoa, good to know. thanks for testing that out.

**Comment by rlskoeser** [comment]
I think we should use meta tags, since it's more current than COinS and should be useful for both Google Scholar and Zotero (and possibly others).

Documentation here: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing 

Not strictly related to this task, but I'd like to include the built in [OpenGraph template](https://gohugo.io/templates/internal#use-the-open-graph-template) and [Twitter card template](https://gohugo.io/templates/internal#twitter-cards).

(Documenting here so I can close a couple of tabs in my browser...)

**Comment by gwijthoff** [comment]
Verified that everything works properly in Zotero, all metadata in its right place.

<img width="390" alt="Screen Shot 2020-06-04 at 2 49 12 PM" src="https://user-images.githubusercontent.com/5580840/84434247-aa45d400-abfd-11ea-8ce5-151a597788ca.png">
