### ISSUE TITLE
As a reader, I want to see an error page if content isn't found.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#30]
# testing notes
to view the 404 page, just enter any non-existing URL like [https://startwords.cdh.princeton.edu/dsflkjasdjf](https://startwords.cdh.princeton.edu/dsflkjasdjf).

# dev notes
this is the 404 page. <s>no design yet.</s>

**Comment by thatbudakguy** [comment]
bumping estimate to a 2, since the design has some non-trivial arrangement of text.

**Comment by thatbudakguy** [comment]
@gissoo this is ready for a look - I'm sure there are small mistakes in some places, I've just been looking at it too long to tell.

**Comment by gissoo** [comment]
@thatbudakguy Thank you!!! I have tested on mobile and desktop (safari, FF, and Chrome)

- the text "ERROR" is not showing up on any of the desktop browsers except when shrunk to max. It also does not show up on FF mobile.
- could you move "ERROR" a bit to the right, more in between the two vertical lines of the 4? It's a bit off to the left right now.
- on the fully shrunk desktop browsers this is how the page looks ![Screen Shot 2020-09-24 at 5.05.37 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/c332b615-a604-4ca6-8b4c-774ab864776c)
Is the all the extra space at the bottom inevitable? 

- What sizing logic are you using for the 404 icon here? Are you using percentages? (if so what is the percentage?)
- @thatbudakguy following the team agreement on Slack I have revised the [404 page here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1104%3A3516) so that: 
1. Everything is now centered on the page for all devices
2. The size of the 404 svg on desktop is resized so that now scrolling is needed.

**Comment by thatbudakguy** [comment]
@gissoo so, I adapted this somewhat to ensure the graphic was always visible on tablet-sized screen, because even with the changes it was often cut off (the text wouldn't be visible below the fold). Now, it will use the mobile styles basically up until desktop. I hope this captures the intent of the design (showing all the image/text) for all screens. I think there are a few sizes (between 600 and 1000px or so) where the image will be a little small, but overall there aren't too many devices in that range and I think it still looks OK enough that this will work as a safe option. Let me know what you think.

**Comment by gissoo** [comment]
@thatbudakguy thank you!!

Just testing this against my earlier notes above: 
1. This looks so much better, I think it's good. Although, on all mobile browsers and Safari desktop browser a bit of scrolling is still required to see the footer but all parts of the visual are visible by default. 

question from my earlier comment, @thatbudakguy:
- the screenshot I took above, the extra space at the bottom is inevitable, correct?

**Comment by thatbudakguy** [comment]
ok, I've made it so that the only difference between tablet and desktop is now the text sizing.

> the screenshot I took above, the extra space at the bottom is inevitable, correct? 

the extra space will expand to fill whatever screen you're using - if you're resizing a desktop browser, maybe that's as small as it will go? if you try using responsive design mode, a real phone, or Browserstack, you'll see that it always fits the device's screen height.

**Comment by gissoo** [comment]
@thatbudakguy this looks much better now!! Thank you.

Yes, I meant the smallest desktop browser as is, wasn't intending to view the mobile version because that looks fine. Anyway, it's ok, it is what you said "the extra space will expand to fill whatever screen you're using" – it makes sense.
