### ISSUE TITLE
Research fonts for displaying Chinese, Japanese, & Kanbun in SW4

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#310]
_This issue tracks design work through the [CDH design review workflow](https://princeton-cdh.github.io/docs/workflows/#workflow-5)._

# Description

Most articles and snippets in _Startwords_ Issue 4 will use Chinese, Japanese, or (possibly) Kanbun characters inline, alongside English text in Latin characters. For example:

> the Chinese classics and texts of the genre of Masters literature (zǐ shū 子書) are astoundingly rich in puns, rhymes, and wordplay.

More examples of how multiple scripts will be used can be found in the latest drafts of each article linked to in the internal "issue overview & status" doc.

We need either:

1) A font that supports Latin, Chinese, Japanese, and Kanbun characters that will work well alongside IBM Plex Serif --- the main body text used on our site, or
2) A new font for all Issue 4 text (articles, snippets, issue introduction page) that includes glyphs / support for Latin, Chinese, Japanese, and Kanbun characters.

Option 1 might find some inspiration from this article, "[Elements of Multi-Script Typography](https://designregression.com/essay/elements-of-multi-script-typography-chapter-2)."

Option 2 would involve detangling Plex Serif & Source Sans from the all of the site's extensive CSS.

# Possibilities Discussed

IBM Plex Sans currently supports Japanese, but won’t support Chinese until Q1 2024 according to the [README](https://github.com/IBM/plex#readme). Our site uses IBM Plex Serif _but not the companion Plex Sans._

Adobe Source Sans, which our site uses as the main sans fonts, supports neither Chinese nor Japanese.

# Additional context on Kanbun

Very few fonts support Kanbun characters. @thatbudakguy shared a webpage that provides a [brief overview of Kanbun](http://www.alanwood.net/unicode/kanbun.html) and lists the Windows and Mac system fonts that support its Unicode block.

It's possible that a font supporting only Chinese (not the Kanbun unicode block) will render the Chinese character in the font's design, with a Kanbun modifier / annotation to the bottom left of the character appearing in a fallback or system font. (Like an English word rendered in the main font, but a subscript footnote number appearing in a fallback font.) I'm curious to know what will happen there.

While Kanbun characters would be nice to have, I don't believe they're used inline in Alíz's article. So we might just include images of Kanbun text. It's not vital to have a Kanbun-supporting font, but it would look much nicer to have Kanbun rendered as text rather than images, and give us more ways to play with the article.

**Comment by thatbudakguy** [comment]
for 1., maybe you could just select and add some typefaces to [_fonts.scss](https://github.com/Princeton-CDH/startwords/blob/main/themes/startwords/assets/scss/_fonts.scss), restrict them to the chinese/japanese/kanbun unicode ranges with [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range), and then put them into the [default sans & serif font-stacks](https://github.com/Princeton-CDH/startwords/blob/75f918780a97d29bf1b954c30ad7680b192f2c34/themes/startwords/assets/scss/_variables.scss#L22-L23) at the front? that way the site would use plex/source sans everywhere except where it needs to represent east asian text, where it would use the other choices instead.

for some figures (SVGs) for our piece, I might play around with subsetting and embedding a [Clerical script](https://en.wikipedia.org/wiki/Clerical_script) font for Chinese, which I think would've been in use at the time our text was compiled. for broad coverage of east asian characters, though, you could use a [Ming typeface](https://en.wikipedia.org/wiki/Ming_(typefaces)) — most systems have one pre-installed, like MS Mincho on windows and Hiragino Mincho Pro on OSX. apparently adobe and google collaborated on one called [Source Han serif](https://en.wikipedia.org/wiki/Source_Han_Serif) too.

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy thank you both!! Just to confirm do we need to support both simplified and traditional Chinese?

**Comment by thatbudakguy** [comment]
@gissoo I don't think so — should be only traditional characters. @GDrom can you think of any reason why we'd need simplified?

**Comment by GDRom** [comment]
@thatbudakguy the only reason I can think of is if anybody cites a publication from the PRC (which uses simplified), and insists on the use of simplified. As far as I recall, Nick and I don't do that; happy to look through Anna's and Xin's contribution to check how they're handling it.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy @GDRom  thank you for your responses and all the information you provided. I have conducted some research and I have a proposal: 

- let's use a different font altogether for the articles that include Chinese and Japanese characters. (i.e. display the Latin characters in that font too)
- If the title of the piece and the metadata at the top of the article do not include any Chinese or Japanese we could keep them as they are in Source Sans and IBM Plex (may end up being easier to change them)
- this would mean the article preview font (the excerpt) may have to change too. 
- Regarding automating the font scaling there are at least two options, 1. is through [this tool](https://www.modularscale.com/ ) that Grant had shared with me a while back – I spent some time testing it and I think we can utilize it, it's really useful for when we already have an existing font system to help us change the scaling, some documentation for SW will be needed to make the process smooth. 2. we can utilize existing design systems such as material design, but this option would just determine the scaling for the new font, irrespective of the site's current font system.  

Justification for the proposals above:
- It is very hard to find one typeface that includes all the characters we need. I could only find one called "Noto CJK", which I then realized is the same as Source Han Serif that Nick had mentioned above, and because it is overall bigger than IBM Plex it is not efficient to put efforts on aligning them in size. (I checked some and it does include the kanbun characters too). 
- I think there is something more meaningful about revising the font only for an article (versus the entire site) to reflect its unique needs. This is something that we need to anticipate for future issues, and it matters because there are no fonts that would satisfy all of our needs (aesthetic and utility-wise) for the SW site. This approach could reveal this challenge with fonts. 

For you to view / Questions 
I have applied the Noto Serif CJK to one of our pieces in the first issue, [you can view it here on Figma](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4404%3A10285&t=FyYLRP5f4gMCOBCo-1), and [see it against the version with IBM Plex Serif](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4406%3A10447&t=FyYLRP5f4gMCOBCo-1) (our current font). I have not scaled it yet, it's a raw transition, we would need to make the base size smaller. @thatbudakguy it would be great if you could tell me what parts of your article I should test with this font. I'd like to see the Chinese and Japanese characters in this font and compare against the Latin. 

Please let me know what you all think about the above.

**Comment by rlskoeser** [comment]
Using an entirely different font for this issue sounds like a lot of work for both designing and implementing updates to all the typography. Or am I misunderstanding? I don't understand how the automated font scaling comes into play. How much effort does that save us? Once we align the base scale of the new font will all the existing sizes work as-is?

Is there a reason we need a single font for all of these characters? Could we select two different fonts and configure with unicode range so they are only loaded when needed? I'm not sure I understand the sizing comment; if it's the size of the font package could we subset them to the unicode range we plan to use?

I don't like opening the door to using entirely new fonts for future articles. What aesthetic and utility concerns do you imagine would require this beyond new character sets / scripts?

**Comment by gissoo** [comment]
> Using an entirely different font for this issue sounds like a lot of work for both designing and implementing updates to all the typography. Or am I misunderstanding? I don't understand how the automated font scaling comes into play. How much effort does that save us? Once we align the base scale of the new font will all the existing sizes work as-is?
> 

- @rlskoeser Just to clarify, my proposal is that the font wouldn't be for the entire issue, it's for the article pages (which may or may not include the metadata at the top of the page, so I'm hoping it's just the body). I'm expecting it will save us a lot of effort, and I'm expecting that adjusting the base scale would would make the current sizes work! Maybe not weights quite, which is why I shared figma link. I am proposing this following our last conversation where I thought you were also agreeing on using one font rather than mixing new fonts with existing fonts in the body of the article. 

> Is there a reason we need a single font for all of these characters? Could we select two different fonts and configure with unicode range so they are only loaded when needed? I'm not sure I understand the sizing comment; if it's the size of the font package could we subset them to the unicode range we plan to use?
> 

- We could do that too, it's a lot less effort on the design side to go with one font. It gives us options for a variety of possibilities with content. There are a number of minor uncertainties on whether there will be any simplified chinese, whether image captions will include characters from more than one language (excluding English). 
- I understand your concern about loading. Will we have image captions that contain characters of more than one language (excluding English)? Will there be a mixture of Japanese / Chinese / Kanbun in one piece and in close proximity? 
- on google fonts, the simplified chinese and traditional chinese fonts are separate, I'd rather not have to use separate fonts for these. @GDRom @thatbudakguy please let's confirm on the need for simplified chinese.
-  [Here you can see a part of Nick and Gian's piece in Noto Serif JP, alongside IBM Plex Serif](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4431%3A10597&t=qTMez1ODvIP0iRFV-1), it needs to be scaled a bit. And [here is what it looks like with just Noto Serif CJK](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4428%3A10366&t=qTMez1ODvIP0iRFV-1)
- @thatbudakguy could you help me figure out the characters in your piece? Google is flagging some as Japanese and some as Chinese but for some reason the Noto Serif JP appears to support both. 
- There is also the Noto Serif Chinese that would be good to use if we decide to omit Noto Serif CJK. 

> I don't like opening the door to using entirely new fonts for future articles. What aesthetic and utility concerns do you imagine would require this beyond new character sets / scripts?
>

- I think in this issue (according to the drafts and what I see) the non-English text is very minimal so I would say it could be fine to just adjust the scaling and display with IBM Plex Serif and Source Sans. But in general when and if dealing with more text it's not ideal because it takes a lot more effort to ensure they appear together coherently. As far as I can understand there is one word in Traditional Chinese characters in Alize's piece, and the rest is in Japanese which will all be contained in the contextual notes. We should confirm this. 
- I'm interested in communicating the lack of a useful and beautiful typographical solutions for these situations, a way to make a statement, so this is an aesthetic concern of mine. Regarding the integration of a new font for a piece it's about supporting a wider variety of possibilities without compromising the reading experience.

**Comment by thatbudakguy** [comment]
The differences between the two seem pretty negligible to me, at least as far as CJK characters are concerned. They both look pretty much how I'd expect.

**Comment by gissoo** [comment]
just to document here: Nick says there is no Japanese text in their article, no kanbun, and they also will not need Simplified Chinese at all.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff updating you on this: 
- based on your feedback I have chosen the IBM Plex Serif + Noto Serif, [here you can see what it would look like for Nick's and Gian's article](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4634%3A10388&mode=design&t=ukqU8SSpN13AYV09-1) and [here you can see what it would look like for Aliz's piece](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4634%3A10491&mode=design&t=ukqU8SSpN13AYV09-1)
- Note: to make them fit better I have reduced the Noto Serif by 2px, i.e. it is always 2px smaller than IBM Plex Serif. On desktop it's 18px and on mobile it's 16px. 

I'll go ahead and close this issue for now.
