### ISSUE TITLE
Create a visualization to communicate the difference between Jingdian Shiwen, dictionaries, and essays. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#314]
Notes: 
- this issue addresses figure 5 on Nick and Gian's article 
- JDSW: notes/annotations on how to pronounce words in ancient classic books. Lu would dedicate a chapter in his book to annotate pronunciations of one classic book.  
- He would pull out the words that were pronounced differently and list them in black, each followed by notes in red specifying where they are in the original book and how they would be pronounced 
- He would annotate the words in a sequential order, i.e. the order of their appearance in the book. (it would be common to read the book sequentially)
- A word he annotated could have come up multiple times in the book and each time it is pronounced differently 
- He could be referring to a single word but may list it with more details (i.e. list it with the words around it) to provide more context and differentiate it from other places the word has been used in the book 
- The dictionaries differed in that they would list the words along with all of its possible pronunciations, so readers could not fully confirm how a word is pronounced at a specific part of the book.

For this visual we should show something that communicates the difference between the two or three versions (JDSW vs. dictionaries vs. essays)

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser @GDROM what do you think about [this version](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4553%3A10533&mode=design&t=5lpTCc5YNgGbLFbb-1) I put together loosely based on your sketch Nick, for comparing the three different approaches?  I've been looking at it for too long, I'm sure it can be improved

**Comment by thatbudakguy** [comment]
here's a bunch of thoughts about this in no particular order:

- it took me a second to notice the texture/color background on some of the text and realize that it's supposed to emulate bamboo/wood. this is a cool idea, but i think it might be too much information for readers, and showing all three types of text (JDSW, dictionary, essay) in this way doesn't completely work since not all texts were actually written on bamboo or wood (some are carved into large stones, for example). 
- if we did want to show the physical writing surface in some way, we'd want to make it look more like this: the writing runs from right to left and from top to bottom, so all of the text types (classic book, dictionary, essay) would need to have their text run in that way.
<p align="center">
<img src="https://upload.wikimedia.org/wikipedia/commons/3/32/Manuscript_from_Shanghai_Museum_1.jpg" alt="thin strips of bamboo with chinese characters in blank ink running vertically">
</p>

- for the same reason, the "ancient classic book" image that we have now is a western idea of a book, with paper pages, page numbers, and text running from left to right. these ideas didn't exist at the time. in fact, the lack of "page numbers" is what makes it so hard to find references in the text! the JDSW doesn't ever have text like "location: p1" because there is no p1. if you want to find where a note for "AB" goes, you have to _already know_ where in the book "AB" is found (because you memorized it, which was relatively common) or you have to go through from the beginning until you find "AB".
- the black vs. red text for source text and commentary is also a nice touch, but i don't think readers will understand it unless we add a legend or label of some kind. if we keep it, I think we should make all of the text in the "dictionary" red, since the dictionary probably won't reference the ancient book directly. we should also make all (or almost all) of the text in the "essay" red, except for a few small "quotes" in black (like the JDSW). so visually, black is text that is taken directly from the ancient book, and red is all other text.
- i think it's important to make the distinction between the JDSW and the essay more clear. for me, the biggest difference is that the JDSW has very short and dense comments that virtually always indicate the same things (how a character is pronounced, how it is written, and what it means). and, these comments in the JDSW are almost always indicated by "marker" characters (like the 反 for fanqie) so that you know which type of comment they are. the essay should probably be "real" text (not scribbles), but it could just be a "wall" of chinese text that doesn't have any labels or anything to indicate what it means, since that's how it appears to the reader.
- i like the decision to include the ancient classic book as its own category of text. i think maybe we should move it up above (or below) the other types of text, just to show that all the other kinds of text are "about" (or at least related to) the ancient classic, and then we can have arrows between them and the classic book just like you have for the JDSW. so, "A" in the dictionary would have an arrow to one (or multiple) "A"s in the ancient classic. and maybe the essay would have a section of black text in quotes, representing a quote from the ancient text, connected to it with an arrow.

**Comment by rlskoeser** [comment]
@thatbudakguy thank you for your detailed comments and suggestions! 

- Nick has addressed in detail my main concern when first from looking at the mockup: the scribbles look like a Western text, which seems problematic
- I agree that the background color distinction is not worthwhile; it's kind of hard to register why it's there or if it matters / what it means
- I did not register the red and black colors as being distinctions in kinds of content

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser thank you both for your thoughtful feedback. [I have revised it a little bit](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4553%3A10533&mode=design&t=ukqU8SSpN13AYV09-1), but there are more issues that need to be addressed which I have not been able to get to this week, will put this issue in the backlog and get back to it later in July.

**Comment by thatbudakguy** [comment]
I think this can be closed. Rather than trying to illustrate the difference between dictionaries, commentaries, and the JDSW, I think it'll be easier to just show an image of an actual (printed) copy of the JDSW, and then indicate to the user what the parts look like on the page.
