### ISSUE TITLE
Contextual notes with more than one child element have separate scroll containers 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#324]
**Describe the bug**
Contextual notes with multiple paragraphs in them display their context in two separate, scrollable, containers stacked on top of one another.

The solution to this might be "just make sure the note has only one child element", but wanted to file it just it in case.

**To reproduce**
1. Go to the article preview for our article in issue 4: https://test-startwords.cdh.princeton.edu/issues/4/unnatural-language
2. Click on contextual note number 8
3. Observe that you can scroll in two separate containers within the note

**Expected behavior**
The entire contextual note should probably be a single scrollable container.

**Screenshots**

https://github.com/Princeton-CDH/startwords/assets/4924494/f8d87817-e4c6-48e6-b206-557252211072

**Device information**
 - Device: MacBook Pro
 - OS and version: macOS 13.5.1
 - Browser and version: Arc 1.6.0 (Chromium 116.0)
 - Site version: preview?

**Comment by rlskoeser** [comment]
Thanks for documenting this @thatbudakguy. I checked in the code and there are two separate paragraphs, no parent container that could be made scrollable instead; since we're working from the html generated from markdown footnotes we don't have a lot of flexibility here.

@gwijthoff are you ok with requiring that footnotes not have multiple paragraphs? Could this just be part of the editorial style guide / editorial workflow?

**Comment by gwijthoff** [comment]
@rlskoeser yes, this solution makes sense to me. Especially because, even in a properly functioning contextual note with multiple ¶s, when a user scrolling down the text encounters a break after the first ¶ they might assume that's the end of the note without being able to see the second ¶ that comes below in the container.

I just collapsed these two ¶s in fn. 8 (I believe the only place it occurs) on the develop branch.
