### ISSUE TITLE
Some figures use serif CJK, others use sans

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#367]
I forget where we landed on using serif vs. sans Chinese characters but seem to recall @thatbudakguy leaning toward serif? Whichever direction we go, they should be uniform, right?

Currently, figures 3, 4, and 6 use serif, and figures 2 and 7 use sans.

**Comment by rlskoeser** [comment]
@gwijthoff Gissoo designed them (or at least some of them) to use sans serif because she wanted it to be more readable. Nick wanted to switch some of them to serif because it was representing historical content. It seems ok to me for them to be different if they are serving different purposes, but I defer to @thatbudakguy on that.

I know he had planned to open a PR with an update to change the ones he wanted updated, but I've lost track whether that's been done.

**Comment by thatbudakguy** [comment]
it has not been done, but I want to – sorry! maybe today.

**Comment by rlskoeser** [comment]
@thatbudakguy if you tell me which figures / or portions or remind me if you already made a note of this somewhere I'll see if I can get to it today.

**Comment by gwijthoff** [comment]
If the intent is to have some sans and some serif, I'm totally fine with that. Just as long as it's not an oversight!

**Comment by gwijthoff** [comment]
Resolved in #373
