### ISSUE TITLE
Design a homepage for mobile + tablet

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#39]
includes:
- featured content + metadata
- a short "about" + link to about
- nav

**Comment by gissoo** [comment]
@gwijthoff, here is the final design for this page on mobile and tablet: 
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1569)

Please take a look and let me know if you have any thoughts or questions so we can revise it :)

**Comment by gwijthoff** [comment]
Hi @gissoo, a few comments:

- the "startwords" definition on the bottom of page should be formatted as a dictionary definition to avoid confusion. It should include the word itself, the fact that it's a noun, and then the two different definitions offset. [See here](https://startwords.cdh.princeton.edu/about/) for an example
- will the ghosted, faded text in the background be lorem ipsum? Or will the text be generated from the article excerpts?
- if we use "read more" *and* the `>` icon at the top of the page, after the excerpted issue description, that will teach users what the icon means. We could also then have the `>` icon at the end of the dictionary definition, rather than the text "Read more about Startwords here."

**Comment by gissoo** [comment]
@gwijthoff Thanks Grant!! Super helpful!

1. I will put the exact language here as it will be helpful (I wasn't focusing on placing the exact copies on other places in the designs as I have not done that everywhere and it's sometimes not necessary to fully do that) 

2. I was hoping it would be generated from the article excerpts, or possibly even longer versions of the excerpts is possible, if not, just the excerpts would be great. (It's very challenging to do this on Figma as I had done it in Adobe Illustrator before, so just left it as lorem upsum text here, will make notes about it on Figma and will tag Nick so he will see it)

3. Great point! Thank you! Let me try this and see how it looks

**Comment by gissoo** [comment]
@gwijthoff I have revised the designs to reflect:
1. the definition paragraph at the bottom of the homepage
2. I communicated to Nick about the ghosted, faded text in the background
3. I changed the "read more about Startwords here" to the red arrow. 

Let me know if you have any questions, or changes in mind so I can revise, otherwise, please close the issue. Thank you!!

**Comment by gwijthoff** [comment]
Thanks @gissoo ! One final question: how would you feel about also including the red arrow icon alongside the "read more" text that's connected to the issue abstract? So, something like:

```
what it's about, and why it was written... read more >
```

That way, users learn what the red arrow icon means when they see it for the first time alongside the text "read more." Not at all necessary, just a thought.

**Comment by gissoo** [comment]
@gwijthoff I thought of this too! But I would recommend to not do it. There will be visually too many arrows on the page that way and it takes a lot of visual attention – which I think can be used in favor of the articles rather than the issue as a first place.

**Comment by gwijthoff** [comment]
@gissoo thanks for your response, makes sense to me!
