### ISSUE TITLE
As an editor, I want to use a shortcode to format pull quotes in articles so that I can call attention to major insights.

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#4]
Hugo allows for custom shortcodes. It would be great to have shortcodes for offsetting text as pull quotes or marginal footnotes / citations / annotations.

https://gohugo.io/content-management/shortcodes/

Pull Quotes
==========

There's an entry for pull quotes in the Tachyons component library: https://tachyons.io/components/quotes/pull-quote/index.html

Margin Notes
============

A collection of CSS techniques based on Edward Tufte's books for margin notes and side notes that reveal between lines of texts on mobile: https://edwardtufte.github.io/tufte-css/#sidenotes

**Comment by gwijthoff** [comment]
@gissoo @thatbudakguy @rlskoeser it looks like pull quotes currently aren't MVP for our first issue launch. But it's occurring to me now that pull quotes would be wonderful to use in RM’s essay, which unlike "Data Beyond Vision" is all text. Pull quotes could visually break up the page a bit more with highlights that draw the eye, in the same way that “DBV” has a lot of visual activity happening on the page.

While I don't think pull quotes are 100% necessary to include in MVP, I'm curious how much time you all think it would take to implement during our next iteration in June (designs from @gissoo, shortcodes written by @thatbudakguy). It would be great if we could make it happen.

![unnamed2.jpg](https://images.zenhubusercontent.com/5e6fa2284847cbacb75fdd35/11974d62-c67c-4ebd-973d-0053b5de4f29)
![IMG_0046.jpg](https://images.zenhubusercontent.com/5e6fa2284847cbacb75fdd35/601c38b9-65b3-411a-965e-b462e7fec7c9)

**Comment by thatbudakguy** [comment]
my initial take is that this is relatively less complex than other features, since it seems like it would boil down to:
- design a unique visual style for blockquotes (maybe the hardest part, honestly...but would defer to @gissoo)
- create a shortcode that wraps some arbitrary content in a [`<blockquote>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)
- write the css that implements the design

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy thanks for writing!!
This came up yesterday in a conversation with Grant. I agree with Grant, it will be very helpful for RM's essay, and glad he caught it! 
Design-wise it's not going to take that much effort, it's fairly simple compared to the other design work that has been done. It will potentially involve adding more text style(s), which is normal and expected for this feature. I think design-wise it makes sense to make it mvp, if you are all ok with it.

**Comment by rlskoeser** [comment]
I agree that this probably isn't that difficult, and would be nice to have.

Might not even need a shortcode, since markdown already has syntax to generate block quotes. IDK if a pull quote should be different than a regular block (seems like we might want both); but maybe it's just a block quote with a css class.

In the interest of keeping scope manageable: is there anything we can drop from MVP if we add this?

**Comment by gissoo** [comment]
@rlskoeser Thanks for writing. I think we decided to drop #27 from mvp, which is worth 2points, does that count?

**Comment by rlskoeser** [comment]
@gissoo sounds good. I think we dropped #27 because it was going to be more complicated than that; looks like the issue hasn't been updated to remove it from the milestone yet. @thatbudakguy do you have a sense of the estimate or do you want to just clear the estimate and add some brief notes about why we're postponing?

**Comment by thatbudakguy** [comment]
I'll clear the estimate and add some notes. Thanks!

**Comment by thatbudakguy** [comment]
Revisiting this - it seems like we can convert this issue to exclusively deal with pull quotes, since our eventual implementation for contextual notes doesn't require a shortcode to differentiate between the different appearances. All that's needed is to write the references (e.g. `[^4]`), so I think that portion is handled - @gwijthoff let me know if you agree.

A shortcode seems like the cleanest way to implement the HTML structure we will need to make the pull quotes match the design, so I think we'd end up using one whether we initially planned to or not. Since pull quotes are now designed, I'm proposing we remove the "enhancement" label and do this as part of the first issue release.

**Comment by rlskoeser** [comment]
This makes sense to me (I was wondering if we had a task to track implementing them). 

Basic pull quotes with a class probably don't require a shortcode (although that might make it easier?).  I think pull quotes don't usually have a source/reference — is that right @gwijthoff ?

I think quotes with a reference probably _do_ require a shortcode to implement properly. I don't think we would use the epigraph/reference in the DBV essay as a pull quote. Is it ok to fold both in and make sure we handle both cases? pull quote without citation and optional right/left; non pull-quote quote with reference.

**Comment by gwijthoff** [comment]
Good call @thatbudakguy — edited the title of this issue and removed the enhancement label. Going forward, we should test the implementation of pull quotes with the dummy text for RM's essay, since hers is the one that will use them most effectively.

**Comment by gwijthoff** [comment]
@rlskoeser that's right, pull quotes are typically a single phrase or sentence. I've never seen one with references or notes of any kind, but that doesn't mean our authors might not want to try it when they see how cool the contextual notes are.

**Comment by thatbudakguy** [comment]
> pull quote without citation and optional right/left; non pull-quote quote with reference.

what's the second case referring to? does it require design? I feel like if @gissoo had known that we weren't going to use the middlemarch bit as a pull-quote - or that they rarely have citations - that might have affected the design, no?

**Comment by gwijthoff** [comment]
Not sure that I'm following here, but FWIW epigraphs and pull quotes are typographically very different. For the sake of simplicity and not adding any new issues, it might be best to assume now that none of the pull quotes in the two articles comprising 1.0 will require any footnotes/contextual notes. They'll just be phrases the editor selects from the text of the piece to draw the reader's eye.

**Comment by rlskoeser** [comment]
@gwijthoff sorry for muddying the waters. Gissoo included the Middlemarch quote from DBV as one of her pull quote examples. I noticed it but didn't comment on it — I didn't expect that we would use that quote as a pull quote but I didn't think it impacted the designs.  Is that wrong?

And never mind about the epigraph style quotes with citations! I see from looking at the DBV draft that it's already handled. @thatbudakguy I presume you took care of this as part of article styles? It looks great.

I didn't mean to suggest that pull quotes could have contextual notes; it would make more sense to me to put any note reference on the main body content that the quote is pulled from. I don't know what kind of complications would arise otherwise, but I'm sure there would be some!

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser  @gwijthoff My use of the Middlemarch quote from the DBV was completely random as I was focusing on text styles, container size, and grids. I have still kept the Middlemarch epigraph in the same layouts, I think. Following what @gwijthoff said I agree that I have also never seen pull quotes with references or notes of any kind. However, I am happy to test the current design for some of these cases for the future issue (after issue 1 if we agree). I completely agree that whatever notes/references a pull quote might have should be right there in the pull quote box at its bottom and visible (not in contextual and end notes).

**Comment by thatbudakguy** [comment]
OK, I've done a first-pass implementation using the new pull quote design. You can see it in action on [Rebecca's essay](https://startwords.cdh.princeton.edu/issues/1/the-body-as-data/) (might need to clear cache first).

@gissoo, let me know if this matches your expectations for a quote without an attribution (since it sounds like that will be the norm).

@gwijthoff, you can see the shortcode in the article text - basically it's just `pullquote` followed by `right` or `left` followed by the text. i was having some fun errors with shortcodes, but this version is the one that ended up working.

**Comment by gissoo** [comment]
@thatbudakguy this looks great! You're awesome!!!!
