### ISSUE TITLE
Design the PDF view for an article 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#43]
- must take into consideration and decide about the presence of:
-  interactivity
- breadcrumbs

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy @rlskoeser Please take a look at my proposed versions of design resolutions for this issue: (https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=164%3A1321)

Note: Design versions are put together in clusters. Please look at one cluster at a time (please avoid jumping in between clusters till you're done with one), please read my notes and the label/name of each canvas carefully as nothing will make sense without reading them. – If they still don't make sense after you read them it will be better to meet so I can go through all of them at once.

**Comment by rlskoeser** [comment]
@gissoo I know you've pulled this out of review to think more about how to approach the contextual notes, but I had a few comments on the other parts of the PDF design.

Are the lines around the footer and header just to indicate size/spacing? (i.e there won't be any actual lines on the page for them)

It looks kind of plain to me; could we include the Startwords logotype on the header on the first page of the PDF? 

And what do you think about using a smaller version of the Startwords logotype instead of just the S logo on secondary pages? I'm not sure how recognizable or identifiable it is outside of the context of the site.

For the page header, why is the article title left and the Startwords logo right? It seems backwards to me, but maybe there is a content hierarchy I'm not thinking about.

Do you think the purple text is distinct enough for the see/touch section? If it's printed in black and white the difference may not be very noticeable, but I don't know how much that matters. I think I love the purple block on the main designs so much that I wanted something closer to that, but I don't know if a line would add anything.

For the footer: the site url is https://startwords.cdh.princeton.edu/; I think we could get by without the http:// since it's pretty recognizable as a url. I do wonder if it should be an article URL rather than a site url (but if so, we should use the DOI and I'd rather have a startwords url).

What do you think about page breaks before the section headings? It might be nice to give them more space.

**Comment by gissoo** [comment]
> @gissoo I know you've pulled this out of review to think more about how to approach the contextual notes, but I had a few comments on the other parts of the PDF design.
> @rlskoeser thanks for writing. 

> Are the lines around the footer and header just to indicate size/spacing? (i.e there won't be any actual lines on the page for them)
> 
- The containers at the top and the bottom are just guides to help see the amount of space, correct, they won't actually be there.
> It looks kind of plain to me; could we include the Startwords logotype on the header on the first page of the PDF?
>
- I put the logotype on header of the first page.
> And what do you think about using a smaller version of the Startwords logotype instead of just the S logo on secondary pages? I'm not sure how recognizable or identifiable it is outside of the context of the site.
> 
- How about only on the first page? The logo itself looks much better to be on the other pages.
> For the page header, why is the article title left and the Startwords logo right? It seems backwards to me, but maybe there is a content hierarchy I'm not thinking about.
> 
- Because this is more logical to me. Because the purpose of this document is the article itself, the person viewing/using this file cares more about "what" this file is than "where" it's from, it's not the right place to highlight "where it's from" as the highest element in the hierarchy. This hierarchy makes the most sense to me. 
> Do you think the purple text is distinct enough for the see/touch section? If it's printed in black and white the difference may not be very noticeable, but I don't know how much that matters. I think I love the purple block on the main designs so much that I wanted something closer to that, but I don't know if a line would add anything.
> 
- I think this looks cleanest, and lines would actually destroy it visually.  
> For the footer: the site url is https://startwords.cdh.princeton.edu/; I think we could get by without the http:// since it's pretty recognizable as a url. I do wonder if it should be an article URL rather than a site url (but if so, we should use the DOI and I'd rather have a startwords url).
> 
- I would defer to Grant, I can put whatever you think will make the most sense. What about the logotype be the link to the site? And we use the DOI? @gwijthoff 

> What do you think about page breaks before the section headings? It might be nice to give them more space.
- Thanks for catching this. I agree with this for all the pages except the first page. Is it possible to increase the spacing on all pages except for the first page? The header of the first page is pretty empty and the space will really help on this page.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy I have put this back for review, and have added one more cluster (derived from the conversation RSK and I had on Monday). Hope to discuss soon. Please read carefully :D

**Comment by rlskoeser** [comment]
@gissoo thank you for all your responses and explanations! I agree with or defer to you on everything you've said. Some follow up comments:
- I like the logotype on the first page; the logo works better for me now that the logotype is on the first page.
- You're right about the page header content hierarchy! I was still thinking web page and not document.
- I don't understand what you mean in your response about breaks before section headings - I don't think we have any section headings on the first page? I'm not sure if we we can apply differentiate styles to the first page or not; maybe only if there are different elements on the page.
- I agree the Startwords logo should link to the site.

I also defer to @gwijthoff on footer content. 

For the notes: I find version 4 of the notes with the triangular shape very visually appealing, but I see what you mean about how distracting they are. I think it's even more distracting than the other versions, because it's actually disrupting the main text. I agree with your suggestion that we use traditional end notes with links for PDF. FWIW, this will also be the easiest solution to implement, and we can do something similar for the plain text version.

@gissoo presuming everyone agrees, will you design the end notes and choose an appropriate return link icon/unicode character that fits with the site? Is there any way to give some kind of visual nod to the way contextual notes will display in other versions? What do you think about a page break before the notes start?

**Comment by gissoo** [comment]
@rlskoeser thanks for writing. 
Regarding the breaks before section headings – I meant on the first page there is less space between the header and the title/metadata of the article than there is between the header and the first line of text that appears on the other pages, and that this is intentional. Is is possible? Because if not, then I would rather match the spacing on the other pages consistent with how it is on the first page. 


Regarding your very last question I think we need to talk, I'm not sure I fully understand everything you intended to communicate here.

**Comment by rlskoeser** [comment]
@gissoo yes, I think we should be able to make the header/metadata spacing different than elsewhere per your intentions.

Happy to discuss end note styles more (with the group, hopefully); sorry my questions are unclear!

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy,

@rlskoeser and I chatted briefly about her comment: "....What do you think about a page break before the notes start? " 

We think on the PDF version it's better to stick to traditional footnotes at the bottom of each page, rather than having them all listed at the bottom of the article (for usability purposes). In this case linking the footnotes won't be necessary either, since they will be within sight. This seems like the best option according to the many conversations above – and the easiest according to RSK, for now. Looking forward to hearing your thoughts.

**Comment by thatbudakguy** [comment]
I agree with the above - simplest option is to do simple bottom-of-page footnotes, no linking needed.

Overall I think everything looks good; the placement of the title at left and startwords logo at right in the header make sense to me. I'm also OK with the small logo (instead of the logotype) on pages after the first one, I think it's fun (but don't have strong feelings).

One thought I keep having is - it seems like this design is converging with print design, which we've talked about. That is intuitive to me - pdfs are digital documents, but they are designed to function like print ones. Does the pdf generation process involve applying CSS? If so, could we write one stylesheet and use it for both print and pdf? That way anyone who prints the website will get the same result as if they had downloaded the pdf and printed it, which would be awesome.

**Comment by gissoo** [comment]
SORRY – Edit: @gwijthoff @thatbudakguy,

Had to delete the previous comment, because there was a miscommunication. 
@rlskoeser and I chatted briefly about her comment: "....What do you think about a page break before the notes start? "

We think on the PDF version it's better to stick to traditional footnotes. 
I think for usability purposes having the footnotes at the bottom of each page, rather than having them all listed at the bottom of the article is better. In this case linking the footnotes won't be necessary either, since they will be within sight. 

However RSK noted that what I said above might be certainly difficult to be done by CSS and RSK recommends them to be all on the same page, at the bottom of the article. In this case, I think linking them will be necessary to make it somewhat acceptable for usability. 

This seems like the best option according to the many conversations above – and the easiest according to RSK, for now. Looking forward to hearing your thoughts.

**Comment by rlskoeser** [comment]
@thatbudakguy - as you see, @gissoo and I had a slight miscommunication about bottom of page footnotes. I agree that it would be a nicer user experience, but I'm not sure it's actually feasible. I can investigate some, but if it's possible at all it's likely going to be difficult. Probably should not be MVP.

PDFs will be generated with print CSS, and my hope is that if someone prints the website they'll get something pretty similar to the PDFs we generate. We have more flexibility and configuration available for generating the PDFs with WeasyPrint (e.g. we could have custom header/footer html files if we needed to do something more complicated - hope to avoid this) and I think different browsers may vary in how they render things, but I'm hoping we can keep the site print very similar to the generated pdf.

**Comment by thatbudakguy** [comment]
agree I'm not sure offhand how to ensure that footnotes always get put at the bottom of their respective page, but i also wouldn't put it past CSS to have some sort of controls for that type of situation...anyway, makes sense to not have it be MVP.

**Comment by gwijthoff** [comment]
All caught up with the conversation now, and I concur with everything above. Awaiting new options for traditional endnotes and footnotes.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy I just finished working on the endnotes since RSK mentioned it's more likely for this version to be MVP. Please let me know what you think. (I'll also work on the footnotes next week, just in case so we see them)

**Comment by rlskoeser** [comment]
The endnotes look fine to me. The only difference I see in the two versions is that you've changed the text of the note. Is there something else I should be looking at?

**Comment by gissoo** [comment]
@rlskoeser no, that's all (just the formatting of the second note)

**Comment by gwijthoff** [comment]
So, the author of an article can has two options for anchoring notes to the main text of their article:

- a traditional note, which will render as an endnote in PDF
- or a contextual note, which in PDF will also render as an endnote but be preceded by the text `(Sidenote)`? Shouldn't that text say `(Contextual note)`?

Or am I reading too much into `(Sidenote)` in endnote 2 on the top right screen of your designs here, @gissoo?

**Comment by gissoo** [comment]
@gwijthoff No, so: The first text that you see which starts with "sidenote" – that whole block of note is taken from what exists as one of the footnotes in the Data Beyond Vision essay draft we have in our google doc (I wanted to use a real note we have written). I am proposing it would be rephrased and reformatted to what I have made it in the second screen. Here, I am not talking about any difference in the notes based on where and how they are displayed, am not sure about that (not mentally there yet), this came up because I am trying to format an endnote correctly.

**Comment by thatbudakguy** [comment]
It looks like the difference in formatting is what constitutes the link text - i.e. whether the link text is the text of the title of the item being linked to, or just explanatory text of what the item is.
- "the paper describing X" vs
- "Talking about X, by Rebecca Koeser"
this seems like either a decision that the content author gets to make, or something that would be decided in our editorial guidelines.

**Comment by gwijthoff** [comment]
Because endnotes (in PDF) and contextual notes (on web) will display the same no matter the content of the note, I will create an Asana task under the editorial section to draft a style guide for authors. This style guide will contain instructions and suggestions for what authors can do with contextual notes in their article.

I also approve of using the article DOI in footer and having Startwords icon link to the journal homepage.
