### ISSUE TITLE
As a contributor, I want to embed 3-D content in pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#44]
# testing notes
like #45, this issue is written from the perspective of a contributor, so it isn't testing the way that the 3d viewer looks - just the _ability_ to embed 3d content if you are writing an article. we will test the look of the viewer as part of #12 since it's part of the design of an article/long piece.

you'll probably notice that the viewer is very wide (it stretches across the screen by default) but may not be very tall. once we apply the design to article pages, the margins will be set, so it will be a more normal size - ignore this for now.

to test this:
- make sure that you have an updated copy of master and check it out locally:
```sh
$ git pull origin master
$ git checkout master
```
- create a new article in any issue by copying one of the existing articles into a new markdown file. change the title (and maybe replace the body content with lorem ipsum or other placeholder text).
- in the new article, use the new shortcode for embedding a 3D model from sketchfab:
```html
{{< sketchfab id="..." title="...">}}
```
- for the value to replace the `...` in `id=`, you can use any model published on [sketchfab](sketchfab.com). grab the `id` by visiting the model's page and copy-pasting the long alphanumeric sequence in the URL bar. here are some examples:
  - a dino vertebra `90af8033ffd348fe83b4338b70cd39be`
  - a cowboy hat `696fb17e3d2a4dd8848af9cec966848d`
  - a jellyfish diorama `f6b97bcd56af4ed6a41caea1c5af2430`
- for value to replace the `...` in `title=`, write your own description for the embedded item. this text will be read to non-sighted users by their screen reader to describe the content in the viewer.
- have a look at the article page for your new article to see how the viewer looks. for sketchfab, many aspects of the viewer are configurable - the lighting and environment around the object, the initial view of the object when the viewer is loaded, etc. if you can think of it, there's probably a way to set it.

if anything seems out of place or broken about the viewer, leave a comment below. if it works like you expect, feel free to close the issue!

**Comment by gwijthoff** [comment]
@thatbudakguy This is the coolest thing I've ever seen. My one question is about the size of the embedded viewer. Will the width of the viewer match whatever margins/padding we eventually set for article text?

**Comment by gwijthoff** [comment]
@thatbudakguy Also: it looks like there's no indication that the image is there [alt text, etc] in the TXT output. Wondering how PDFs will handle 3D content as well.

**Comment by thatbudakguy** [comment]
@gwijthoff yeah, when we set margins for the whole article it will cause this (and the deep zoom viewer) to conform to those margins.

it's a good point about the txt output, thanks for reminding me. I'm not sure how to handle it, offhand...maybe @rlskoeser has an idea?

the only thing I could think of would be to do a similar `replace`call using something like a regex, and replace `<img>` tags or `<iframe>`s with their `title` or `alt` attributes, so it would say something like 
```
text...
[image of (whatever you put for the title= attribute)]
more text....
```

**Comment by rlskoeser** [comment]
@gwijthoff I think we'll need fallback images for 3D and deep zoom for the PDFs; @thatbudakguy and I have discussed it but decided to hold off on implementing anything for now because we don't know enough — but maybe we should create issues to track that, because we'll need to do something.

I'm hoping we can come up with a way for the plain text version to include the same content that a screen reader would hear, and would love if we can leverage CSS for that as much as possible rather than adding more regexes to our plain text version (maybe if we use separate elements and associate with aria attributes?). I can see the need for regexes to add labels (roughly equivalent to what a screen reader might announce for an image), but I think we should try to keep any text replacement logic as simple as possible.

Should we add an issue to track adding/handling alternate content for plain text output?

**Comment by thatbudakguy** [comment]
created #56

**Comment by thatbudakguy** [comment]
closing since notes about how to represent the viewer in pdfs/in plaintext are now captured on other issues.
