### ISSUE TITLE
As a reader, I want the header navigation to get out of the way when I'm reading text.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#66]
# dev notes
this corresponds to the "pit bar" behavior as seen on the header navigation on the cdh website and on PPA.

**Comment by thatbudakguy** [comment]
bumping to a 2 since I had to rewrite the PPA version to take out jQuery and use es5 semantics.

**Comment by thatbudakguy** [comment]
this is ready for :eyes: from @gissoo and @gwijthoff!

**Comment by gwijthoff** [comment]
Omg this looks so slick and perfect. I'm not crying you're crying.

**Comment by gissoo** [comment]
@thatbudakguy Thank you for working on this!!! Just having looked at the "About" page and playing around with the narrowest view on all desktop browsers, could we make it so that it will get out of the way with much less scrolling? This way we will cover for short pages such as the about page (on mobile, and narrow desktop view) as well as for the article page on narrow desktop view. 

My definition of "much less scrolling" is that, for instance, on the article pages the nav would get out of the moment you start to scroll.

**Comment by thatbudakguy** [comment]
@gissoo OK, I've tweaked the behavior a bit:

- on desktop, the nav doesn't hide itself at all, since there's always space (h/t @rlskoeser for this idea)
- on mobile/tablet, it now hides as soon as you scroll down (any speed).
- if you scroll up slowly, it won't come back, but if you scroll up somewhat quickly it will (this can be adjusted).

let me know what you think. note that if you want to test the behavior on different screen sizes (if you're using a desktop browser and resizing it) you need to **refresh** after you change the screen size.

**Comment by gissoo** [comment]
> @gissoo OK, I've tweaked the behavior a bit:
> 

@thatbudakguy thank you for working on this!! 

>     * on desktop, the nav doesn't hide itself at all, since there's always space (h/t @rlskoeser for this idea)
> 

- @thatbudakguy @rlskoeser I think the reason I didn't say anything about this before is because I find it necessary for the nav to hide itself on desktop, for when the desktop window is shrunk. I think it's important that the content is still readable even if the window is at its narrowest. It's now blocking the left part of the text. 

>     * on mobile/tablet, it now hides as soon as you scroll down (any speed).
> 

- Yes, works perfectly!

>     * if you scroll up slowly, it won't come back, but if you scroll up somewhat quickly it will (this can be adjusted).
> 

- It still comes back when I scroll up slowly. 

 
> let me know what you think. note that if you want to test the behavior on different screen sizes (if you're using a desktop browser and resizing it) you need to **refresh** after you change the screen size.
>

- Thanks for the tip! Useful to know. 
- @thatbudakguy There is one issue, which is that on iOS FF, Chrome, and Safari, after 3-4 times of scrolling up and down, once you reach the top most part of the page, the nav goes away again and does not come back, not sure why this is happening.

**Comment by thatbudakguy** [comment]
> nav to hide itself on desktop, for when the desktop window is shrunk

our breakpoints are sized in terms of the viewport width, so when I say "desktop" here I mean any screen that is at least 1024px wide. if you change the window size to be smaller, the styles that are applied will match the screen size, so if you shrink the window it's not technically "desktop" anymore. can you say more about your intention here?

> It still comes back when I scroll up slowly. 

how slow are you going? using safari's mobile device emulator as a iPhone SE I can get it to stay hidden if I scroll up at a slow reading speed (one or two lines per second). any faster than that should trigger it.

> the nav goes away again and does not come back, not sure why this is happening. 

I can't duplicate this using the mobile device emulator either. Could you maybe post a video so I know how to trigger the behavior?

**Comment by gissoo** [comment]
> > nav to hide itself on desktop, for when the desktop window is shrunk
> 
> our breakpoints are sized in terms of the viewport width, so when I say "desktop" here I mean any screen that is at least 1024px wide. if you change the window size to be smaller, the styles that are applied will match the screen size, so if you shrink the window it's not technically "desktop" anymore. can you say more about your intention here?
> 

- @thatbudakguy Thanks for writing. The nav does go away on iOS (mobile). It doesn't go away when I'm trying to use the website on a narrow browser on desktop. This is why I referred to it as "desktop" to avoid other types of confusion. My intention here is that I am interested to see what happens if the user decides to narrow their window (if they have multiple windows open simultaneously and/or need to make their window narrow for other reasons can our site still be usable to them? It's currently not without the nav hide on desktop) With these situations my general preference is to apply the nav hide feature to desktop even if it doesn't affect the wide/normal desktop view, so that even when you choose to narrow your desktop window you can use the site. 


> > It still comes back when I scroll up slowly.
> 
> how slow are you going? using safari's mobile device emulator as a iPhone SE I can get it to stay hidden if I scroll up at a slow reading speed (one or two lines per second). any faster than that should trigger it.
> 

- thanks, yes, I just checked again, that's almost always the case (kind of inconsistent, especially on iOS FF), but this doesn't matter so much. It's works well. 

> > the nav goes away again and does not come back, not sure why this is happening.
> 
> I can't duplicate this using the mobile device emulator either. Could you maybe post a video so I know how to trigger the behavior?

- @thatbudakguy Sure, will send my video on Slack.

**Comment by thatbudakguy** [comment]
> if they have multiple windows open simultaneously and/or need to make their window narrow for other reasons can our site still be usable to them? It's currently not without the nav hide on desktop

the issue is that the nav behavior assumes that people's devices generally don't change screen size, since resizing windows to be pretty small is kind of an edge case (you would expect most sites to look pretty different). if you resize the window _and then_ refresh, you would get the correct behavior. just for fun, i played around with adding resize detection to the pitbar; go ahead and try resizing it now (without refreshing!) and see if it picks up the new size.

**Comment by gissoo** [comment]
@thatbudakguy Omg!!! Thank you!! I didn't know there is a way to do that ...I thought the only way is to enable it for "desktop" ...Thanks for helping me learn!! This is cool!! It works now. This is so much better!!

**Comment by thatbudakguy** [comment]
@gissoo is this ready to close, or are you still seeing strange behavior when scrolling?

**Comment by gissoo** [comment]
@thatbudakguy the only reason I didn't close this was because I sent you a [video here and you responded to it](https://cdhprinceton.slack.com/archives/CR6JCFQHE/p1593107136177100)

Has this been revised/fixed?

**Comment by thatbudakguy** [comment]
> Has this been revised/fixed?

that's what I was asking:
> are you still seeing strange behavior when scrolling?

I don't have any way to replicate this bug, so I don't know if it's changed now that I adjusted the scrolling timing/behavior. Can you check again?

**Comment by gissoo** [comment]
Sorry :D I meant "have you addressed it?" – Let me test it

**Comment by gissoo** [comment]
@thatbudakguy yes this is still an issue on iOS FF, Chrome, and Safari.

**Comment by thatbudakguy** [comment]
ok, thanks for testing - I'll see if I can get a device that will replicate it (maybe Hannah's iPhone will work).

**Comment by thatbudakguy** [comment]
borrowed Hannah's iPhone to debug this and I _think_ I have a solution implemented now. @gissoo it's ready for another look when you have a chance.

**Comment by gissoo** [comment]
Thank you, @thatbudakguy!! YAY! It's fixed on iOS Safari and Chrome!!! 
But it's still happening on iOS Firefox.

**Comment by thatbudakguy** [comment]
See comment on #90 - I think we should close this anyway, since mobile FF is an edge case and it may resolve over time on its own.

**Comment by gissoo** [comment]
Thank you, @thatbudakguy, so helpful. I agree, I'll close.

**Comment by gwijthoff** [comment]
Not to belabor this issue (agree that it should be closed), but I just discovered that on Firefox Focus (their privacy browser), the scrolling *does* work in long notes! 🤷‍♂️
