### ISSUE TITLE
Guidelines/styles for images in contextual notes on PDF and end note display

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#75]
Thinking about this because I'm looking at the DBV essay; #73 only provides styles for images when they appear in the contextual notes container. How will we display those same images in the end note / PDF version of the same notes?

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy Please take a look at [the desktop, tablet, mobile, and pdf article pages here and read my notes](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766). Please let me know if they don't make sense, we can talk through them.

**Comment by thatbudakguy** [comment]
PDF designs make sense to me; centering the images at a fixed width seems good. I think we can do the same thing on all screens as well: just center the image at a fixed width and stack it. I don't think we want to make the image even smaller than it appears in a contextual note; on mobile especially it seems like it would be very difficult to make out details in such a tiny image. If we use the same display format for PDF and all screens, that keeps things simple in the CSS.

Maybe I'm missing something, but why do the notes for the screen designs say "Max number of icons..."? Aren't icons a totally different thing?

**Comment by rlskoeser** [comment]
These designs seem good to me. Glad to have clear min/max widths, and the plan to stack the images makes sense to me.

@thatbudakguy we're not implementing styles for icons now, but Gissoo wanted to document recommended guidelines for how we would display them while she worked on the images, since the use cases are so different. (@gissoo did I remember that correctly?)

@gissoo one note about the markdown footnotes: the return to text link is going to be at the end of the note, whatever content it includes — potentially including images. If the images are the last thing in the note, then the return link will come after them. I want to mention as an FYI in case you have concerns and also so you can suggest where the return link should be placed in the case where an image is the last thing in a note, with no text after the image.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser thanks for writing! I agree with your points. Yes Nick, RSK is right about the icons, I just want to document them, because if we were to display an icon there instead of an image it should not be as large as an image would be. Thanks, @rlskoeser.
[I have revised the designs, here.](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766)

**1.** I have revised so that everything is now similar with the approach on PDF. Although, I think it makes sense that:
- a maximum of 2 images and/or icons with min width would be displayed in one row on desktop and tablet. 
- a maximum of 2 icons with min width would be displayed in one row for PDF. (not for images, since the PDF margins won't allow it)

This being said, I'm flexible if you want to stack them at all times, I just think what I'm suggesting is visually better, but not worth it if it makes things a lot harder/more complicated.

**2.** I have revised so that now on all screens (for endnotes) you can see:
- an endnote where an image/icon is the last item of the note and 
- another one where an image/icon is in the middle of the note. In this case, I think it's best if we wrap to make sure the image/icon is on a separate line from the text and as I checked with RSK she said it's possible to do it.

3. you can also see how I have chosen to display the return to text link for both of the bullets above in no.2. For the second bullet above, I think it's best if we can display the return link after the image/icon on the same line rather than a separate line below the image/icon. This is specifically on desktop, tablet, and PDF because the text and image margins here make it harder to find the link when it's on a separate line. (it's easier to see/find/notice it when on the same line), it's okay and works if it's below the image/icon on _mobile_ because the issue with the margins doesn't exist here and items are all more within sight and tighter in general. 

This being said, I feel a bit strongly about this, but if you think it's too complicated to place it on the same line as the image/icon I can compromise.

**Comment by rlskoeser** [comment]
@gissoo updates look good to me.

**Comment by gissoo** [comment]
@gwijthoff [please take a look at the designs here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766)

Please read the notes next to the pages
Please zoom in enough to read the title of each page/artboard. 
There are two clusters here that are important to look at (mainly the desktop,tablet, mobile and pdf pages – we had already agreed on the contextual note ones): 
1. one cluster is for when there are images (i.e. photos) that need to be shown in the endnotes 
2. the other cluster is for when there are icons that need to be shown in the endnotes 
Note: the sizes for both the images and icons on these pages (desktop,tablet,mobile,pdf) are all based on our previous agreements about how they are displayed in a contextual note itself (which you can see on the left of this page).

**Comment by gwijthoff** [comment]
Hi @gissoo, question: in the example endnote 4, desktop and tablet versions contain two images or two icons. But on mobile, endnote 4 only has one image or icon. What happens to the second image/icon for a mobile user?

**Comment by gissoo** [comment]
@gwijthoff omg, thanks for catching!! I have fixed it. They will stack on mobile. They are there now, if you want to take a look.

**Comment by gwijthoff** [comment]
@gissoo cool, glad to see them stacking now. Really excited to see this implemented in practice! An *image*? In an *endnote*? ::swoon::
