### ISSUE TITLE
Design the homepage for desktop 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#76]
Note: the font sizes for desktop are new. (sized up by 2 pixels from mobile/tablet, except for the large THEME text on the issue list page, which has been sized up by 10 pixels from mobile/tablet).

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @thatbudakguy 
[Please take a look at the design here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1569) and let me know what you think.

**Comment by rlskoeser** [comment]
Seems fine to me. Defer to @thatbudakguy @gwijthoff

**Comment by gwijthoff** [comment]
@gissoo love those text shapes with the extra roominess on desktop. Looks great!

**Comment by thatbudakguy** [comment]
again, love the choice to bump up the font slightly but otherwise let everything scale naturally. looks great!

**Comment by gissoo** [comment]
@thatbudakguy What do you mean by "let everything scale naturally"? What is everything else? Everything I am showing here with how things are falling on the grids on desktop are intentional, and natural in my logic, but worth clarifying if you disagree :D before this is implemented.

**Comment by thatbudakguy** [comment]
sorry, what I meant by that was "keeping the same relative sizing for elements". so, the main container spans grid-columns 4 to 8 on tablet - we keep the same values for desktop, but because the grid itself expands to fit the screen, the content also "naturally" expands. thus I don't have to write any new code.

fonts currently don't "naturally" resize themselves when the screen gets bigger, because their sizing isn't tied to the width of the viewport. so, the changes to font sizes are new code that I have to add (but of course it's very trivial).

both changes are natural logically to me, it's just that one of them doesn't happen "automatically" (though we could make it more or less automatic by changing the root font size when switching breakpoints, and I'd love to talk with you about that some time!)

**Comment by gissoo** [comment]
@thatbudakguy thanks for writing, this helps! Since you and @gwijthoff and @rlskoeser are okay with this, I'll close.
