### ISSUE TITLE
Design the single issue page for desktop

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#78]
Note: the font sizes for desktop are new. (sized up by 2 pixels from mobile/tablet, except for the large THEME text on the issue list page, which has been sized up by 10 pixels from mobile/tablet).

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy [Please take a look at the designs here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736) and let me know what you think.

**Comment by rlskoeser** [comment]
@gissoo why is the purple arrow on the first screen higher on desktop than it is on tablet? 

Otherwise, this all seems fine to me.

**Comment by gissoo** [comment]
@rlskoeser Thanks for writing, it was not intentional, they are fixed now, thanks for catching.

**Comment by rlskoeser** [comment]
Ok, everything here looks good to me now.

**Comment by thatbudakguy** [comment]
I'm not sure how the logic of this page that we've been going with so far (treat the two "parts" as two separate screens) translates to desktop. One way to interpret the desktop design would just be to limit the white upper portion to the height of the artboard, which looks like 552px (not sure where this number comes from). In that case, you would always see both the purple and white sections together on the same page, which might be fine - it just seems like the logic that underlies the arrow doesn't really hold up on desktop, where the user doesn't need to scroll very much (if at all). It's easy to implement, but leaves me with the feeling that I'm viewing a mobile-like page that is modified or stretched to fit my screen (which is exactly what's happening) rather than an actual desktop-like experience. Put another way, I think this page might require more deviation from the mobile/tablet designs in order to "make sense" or feel natural on desktop, because the mobile and tablet designs include some logic or assumptions that don't really apply on a larger/taller screen. Hope this makes sense.

**Comment by gwijthoff** [comment]
I think I agree with @thatbudakguy that the logic of scrolling from one separate screen to the next (or "cards" as we metaphorically referred to them) doesn't translate well to desktop.

> leaves me with the feeling that I'm viewing a mobile-like page that is modified or stretched to fit my screen 

Agreed.

Would it help to put roughly 300 words of lorem ipsum into the article description to get a better sense of the relationship between elements?

Personally, I wouldn't have a problem with seeing both purple and white sections together on the same page on desktop. But maybe @gissoo has another solution in mind.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff  Thanks for writing. There may be some misunderstandings on this so we need to hash out some details that may be overlooked and not explicit. So, the 552px is just a random height here. @thatbudakguy because we had decided to use 1024 for desktop width instead of 1440 and 1024 does not exist as a standard screen option on Figma. Is the height of a not-scrolled desktop page 768px? If so, I can increase it to that so that it's more clear. What the design here has always intended has been to only see one background color at a time, where the purple arrow will take you to the purple background and snaps it in place for the user, I was implying this idea somewhat through using two different artboards with two different background colors in Figma, otherwise I would have used one artboard to show both pages. I really think doing anything other than this on desktop won't be valuable.

**Comment by thatbudakguy** [comment]
> Is the height of a not-scrolled desktop page 768px?

i think this is a good value to use, since it's a common desktop resolution (1024x768) and also the resolution of an iPad rotated 90 degrees.

> What the design here has always intended has been to only see one background color at a time

great - this is the impression I got, too. it's kind of a "two-screen" experience where the user toggles between the two "screens" using the arrow. if you look at the production version of the site now on desktop, that's what should happen: the first "screen" fills the whole window, regardless of how big your computer is, so there will be a lot of empty space. when you click the arrow, you jump to the purple part, which also fills the entire screen.

**Comment by gissoo** [comment]
@thatbudakguy thanks, yes, great. Revised the heights. If everything looks good, let's close @gwijthoff @rlskoeser

**Comment by gissoo** [comment]
Since no one closed and everyone is on the same page, I did.
