### ISSUE TITLE
Design a way for the user to access all the short pieces that an issue contains so they can read them. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#86]
- Where are links to short pieces that are independent from any long pieces? (also, where do they live? Can we make them more easily accessible? – Currently they are only under the Single Issue page)

**Comment by gwijthoff** [comment]
The way they're currently positioned, the list of short pieces on the issue page is a bit confusing. I imagine that a reader might be confused about their purpose and relationship to the issue's other elements.

Can we set them off with a different header of some kind? 

![Screen Shot 2020-06-23 at 3.18.40 PM.png](https://images.zenhubusercontent.com/5e6fa2284847cbacb75fdd35/db605559-d7ff-4e25-9e71-d20326fb22a5)

**Comment by gissoo** [comment]
@gwijthoff @rlskoeser What do you think of [this design](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736)? (the bottom of the purple portion on all devices – and the section header/title idea)

Am I way off on some previous agreements? Sorry, I feel like this was discussed forever ago, let me know if you think I'm missing something important here.

**Comment by rlskoeser** [comment]
@gissoo I don't know how much we discussed because I think we were always kind of vague on what the short pieces where or we had different ideas of what they might be. (I mean, I had ideas about it but clearly I did not communicate them well! 😆 )

You've included the things I'd like to see — title, authors, and a tag indicating what _kind_ of thing it is. 

@gwijthoff would you want to add an editorial comment or introduction about the "short pieces" included in a volume that could be displayed with them (in addition to the main issue intro at the top of the issue page)? I feel like we discussed before not knowing how to label the short pieces because we didn't know enough yet. Do you know enough now to come up with a general intro that you can live with for now?

🤔 is there anything clever we can come up with riffing on startwords / stopwords to label these short pieces? (middle words? midwords? ) 

Another thought: would a section break work here to separate the featured articles from the short pieces? 

This layout doesn't address @gwijthoff's previous concern — it looks like they are all associated with the left side story. True in this case, but we don't know about that in the future and had decided to keep the metadata simple and link them manually in the article content.  @gissoo would it help to put them in a narrower block that is centered under the two main articles? Or do you want to suggest something else?

**Comment by gissoo** [comment]
@rlskoeser Thanks for writing. In my opinion, the current layout for the short piece section (how it's extending to take the full width, and its header, "More pieces to read" are addressing Grant's concern. I'm not sure a section break is helpful here, I prefer we don't do that here. I tried to make the width narrower but it's worse, it looks like it's part of the content above it. I think a header like "more pieces to read" will help. I can experiment with another style of section break if this is not enough. To me, it's sufficient right now (someone who has never looked at this page will not think that there is any association between the short pieces with the "data beyond vision" essay.

**Comment by rlskoeser** [comment]
Thanks for explaining @gissoo — this all makes sense and am happy to defer to your judgement on section break (and interesting that you tried the narrower width and it was worse!). I've probably looked at this page too many times, it's hard for me to think what someone new to it will think.

**Comment by gwijthoff** [comment]
@rlskoeser @gissoo thanks for all your notes here! Some thoughts:

- if the heading for this section of short pieces is in all caps, or [smallcaps](https://en.wikipedia.org/wiki/Small_caps), I think it would be set off from the two features even more clearly, so that the reader doesn't think the short pieces are associated solely with the feature on the left side of the page.
- any description of the short pieces would probably be best included in the larger editorial introduction above, rather than adding any prose to the list of short pieces
- some startwords-related names for this section:
    - [morphemes](https://en.wikipedia.org/wiki/Morpheme)
    - KWIC
        - from [this great article on the history of stopwords](https://www.jstor.org/stable/10.1525/rep.2014.127.1.83): "In the 1950s, Luhn’s most influential achievement was the KWIC (Keyword in Context) index. KWIC, which achieved popularity in a wide range of academic and business contexts, was a‘‘permuted’’ or, more properly, a ‘‘rotated’’ index. It took the words of a text,excluding stop words, and generated an alphabetized list of passages giving contextual words before and after each."
        - could be something like "KWIC Pieces" or "KWIC Takes." Or even just "Keyword in Context."
    - stop list
    - bag of words
    - function words
    - snippets

**Comment by gissoo** [comment]
> @rlskoeser @gissoo thanks for all your notes here! Some thoughts:
> 
>     * can we try one more thing to further set off the list of short pieces from the feature on the left side of the page even more clearly? We could make the header text above the list of short pieces either
>       
>       * all caps
>       * [smallcaps](https://en.wikipedia.org/wiki/Small_caps)
>       * or with a similar/identical font weight to the titles of the two features
> 

@gwijthoff I have tried it with both all caps and small caps so [you can see here ](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736) – I originally did not want to use all caps and I'm not really a fan of it here. I think small caps is a better solution that I hadn't thought of, thanks for bringing it up – however I'm not sure about its implementation, because I'm now using the "force small caps" option in Figma as the normal option does not work, I'm thinking if this font doesn't offer the option – I also would strongly like to avoid using a similar/identical font weight to the titles of the two features because systematically it's problematic and I intentionally didn't try it, because the title of the short pieces should be similar to the titles of the two features. 

>     * any description of the short pieces would probably be best included in the larger editorial introduction above, rather than adding any prose to the list of short pieces
> 

I agree! This makes sense.

>     * some startwords-related names for this section:
>       
>       * [morphemes](https://en.wikipedia.org/wiki/Morpheme)
>       * KWIC
>         
>         * from [this great article on the history of stopwords](https://www.jstor.org/stable/10.1525/rep.2014.127.1.83): "In the 1950s, Luhn’s most influential achievement was the KWIC (Keyword in Context) index. KWIC, which achieved popularity in a wide range of academic and business contexts, was a‘‘permuted’’ or, more properly, a ‘‘rotated’’ index. It took the words of a text,excluding stop words, and generated an alphabetized list of passages giving contextual words before and after each."
>         * could be something like "KWIC Pieces" or "KWIC Takes." Or even just "Keyword in Context."
>       * stop list
>       * bag of words
>       * function words
>       * snippets
>

@gwijthoff I love these!! I like morphemes, keyword in context, and snippets!!! Thanks for suggesting these!!

**Comment by rlskoeser** [comment]
I like snippets and small caps if we can do it.

**Comment by gissoo** [comment]
@gwijthoff please review this issue and close if ok (my final comment above has a link to the designs)

**Comment by gwijthoff** [comment]
@gissoo thanks for all of these options. If we can implement it, I think I prefer the small caps option, like RSK. It looks distinct enough to me from the feature titles, and is also clearly distinct from the short piece titles.

**Comment by gissoo** [comment]
@gwijthoff Great, thank you! 

I made noted that small caps version is our final decision and the all caps only if the small caps won't work well, [here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736). @thatbudakguy just so you're aware. I'll go ahead and close this issue.
