### ISSUE TITLE
add custom css for dbv essay

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#88]
# dev notes
[figma design](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2295)

we need special css to handle:
- [x] the purple sections ("TOUCH", "SEE") and their images
- [x] the clickable icon blocks
- [x] the section headers with icons
- [x] the background image of the weaving
<s> pdf styles </s> moved to #147

there's already a `style.css` file in the content folder for the essay, so we just need to add to that.

**Comment by thatbudakguy** [comment]
tagged everyone for review on this one, just because it's a big one and more eyes is probably good.

one notable difference from the design is that the margins of the purple section (I call it an "interlude" in the code, not sure what else to call it...) are less tight on desktop...they seemed incredibly restrictive and I was having trouble making the text fit right; went with a margin more similar to the homepage or issue list page instead. @gissoo let me know if this doesn't make sense to you.

haven't tested to see what the pdf looks like, hoping for help from @rlskoeser or @gwijthoff on that.

**Comment by gissoo** [comment]
@thatbudakguy Thank you!!! So exciting!! I tested on all browsers mobile and desktop. Everything looks fine as far as I noticed, and tested also by clicking on all the icons, feeling a bit dizzy now :D – I think it's all fine, I'll check again tomorrow just in case. 

A couple of things I noticed: 
1. The position of the weaving icon above its section heading is off/doesn't match the design on both mobile and desktop. desktop version shown here: [Screen Shot 2020-09-30 at 5.35.25 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/a379e149-e371-4240-afa6-9cc474a86133) 

2. The first list of icons the white background should cover the weaving image, right now it's below the weaving image: ![Screen Shot 2020-09-30 at 5.33.26 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d112ccdf-e2ef-4e88-9eb0-9c329b321e46)
- Also, if you notice in this screenshot the icon list looks larger on firefox than on other browsers, this is _not_ happening on mobile, not sure how much it matters, it's just weird. 
 
3. The hand icon on the purple background is missing the wrist, can we include it? I really appreciated the wrist :D Let me know if it creates any issues or if I can do something about it. 

4. Also, in my designs the list of clickable icons decreased from 4 to 3 to 2 ....I like your logic better that always 4 icons appear, however I'm wondering if at some point we could also use this to visually indicate where on the page the person is (like after icon 2 or 3) ...i.e. what they have read from what they haven't read, is this worth to pursue? @thatbudakguy @rlskoeser

**Comment by thatbudakguy** [comment]
1. good catch; I've adjusted it so that it's centered now.
2. this z-index issue should now be fixed as well.
3. on very small screens (mobile to about 500px) there's not enough space for the wrist (it runs into the text), but I've now moved the hand out so you can see the wrist on tablet and desktop.
4. i've thought about this too...i can see including some kind of "active" indicator, but i think it requires further design. i'm also not totally convinced it's necessary, since theoretically you can know where you are because the active heading will always visually be right below the clickable list (see pic). would be curious to hear other's thoughts though.

![Screen Shot 2020-10-01 at 12.56.08 PM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/d448532c-8f83-49d9-820b-c3658322ba5c)

**Comment by rlskoeser** [comment]
Regarding #4: In the draft, I had all four icons listed the first time you see "choose an object", and then had imagined the one after a section would say "choose another object" and show you everything but the one you just finished looking at. 

@gissoo 's idea about status is pretty appealing. @thatbudakguy could we use `:visited` to de-emphasize anchor links that have been clicked?

**Comment by rlskoeser** [comment]
@thatbudakguy is there a reason you haven't tested the PDF? I'm pretty sure you'll need to adapt the custom styles for print, from what I remember of Gissoo's designs. Just did a quick weasyprint run and lots of things are missing or wonky.

**Comment by thatbudakguy** [comment]
@rlskoeser are there instructions anywhere about how to generate the PDF? I don't have weasyprint installed and have never used it, which is why I tagged you and grant.

**Comment by rlskoeser** [comment]
@thatbudakguy sorry, when you said you were hoping for help you meant you needed directions? Sorry, thought you wanted help testing/reviewing it.  I was wondering about directions.... I may never have written anything up! 😞  Perhaps in part because it wasn't clear where they should go or what we need to document. (Google doc? Theme readme?)

See the weasyprint installation instructions: https://weasyprint.readthedocs.io/en/stable/install.html
It's a pip install, but there are some dependencies you need that you may not have.

Once it's installed, you just run it with a url and the pdf filename you want to generate.  (There are a lot of warnings, but everything seemed fine to ignore when I was working on it before.)

I found it difficult to inspect the PDF styles (and it's also slow to regenerate every time you change things); you can get a lot of mileage out of simulating it in the browser. Chrome has a way to simulate print rendering, I imagine FF does too. It doesn't display everything the same way weasyprint will render it, but still very helpful.

**Comment by gissoo** [comment]
@thatbudakguy thank you for working on this, as we mentioned on Slack, would you please revise [this issue that I found last week with the stacking icon](https://cdhprinceton.slack.com/archives/CR6JCFQHE/p1602798023172400) before I review?

**Comment by thatbudakguy** [comment]
@gissoo ok, I've addressed the the icon issue.

**Comment by gissoo** [comment]
>     1. good catch; I've adjusted it so that it's centered now.
> 

- In the designs it's not centered, just like the other icons it's at the most right edge of the rectangular background.

>     2. this z-index issue should now be fixed as well.
> 

- Yup, looks great!

>     3. on very small screens (mobile to about 500px) there's not enough space for the wrist (it runs into the text), but I've now moved the hand out so you can see the wrist on tablet and desktop.
> 

- I  can see it! 

>     4. i've thought about this too...i can see including some kind of "active" indicator, but i think it requires further design. i'm also not totally convinced it's necessary, since theoretically you can know where you are because the active heading will always visually be right below the clickable list (see pic). would be curious to hear other's thoughts though.
>
> ![Screen Shot 2020-10-01 at 12.56.08 PM.png](https://camo.githubusercontent.com/5e07b86c518e1db6f15108d8fb50ace8b92dd04b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561613832633462346235383036626332626361623466612f64343438353332632d386638332d343964392d383230622d633336353833323262613563)
>

- I think it's still useful to do especially since that container just keeps visually repeating on the page. 
I can see the use of fade, or some marker under each icon that when its section has been viewed. 
To your point, even though they are always visually right below the clickable list, only one of them is immediately seen below, but there is not an immediate way to know all of which haven't been viewed yet. 

- Is this the place where we should discuss the max line length for various screens? 

- Also, do you know by any chance why [(in my screenshots above)](https://camo.githubusercontent.com/f2ef2774fcf54088f93545bed1c5b6aacb009b79/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562663330376136396435393562343539656339316262312f64313132636364662d653265662d346538382d396562302d396333323962333231653436) the size of the icons in the list is different on firefox vs the other two browsers? The icons look smaller on the other two browsers – this is not a big deal but wondered if you intended that?

**Comment by thatbudakguy** [comment]
> In the designs it's not centered, just like the other icons it's at the most right edge of the rectangular background.

oooooops good catch. should be fixed now

> To your point, even though they are always visually right below the clickable list, only one of them is immediately seen below, but there is not an immediate way to know all of which haven't been viewed yet. 

for #150 I've switched it to show the icons for all of the sections except the one you're currently viewing in the icon nav; you can [see the preview of that here](https://startwords-pr-152.onrender.com/issues/1/data-beyond-vision/). the first set of icons shows all of them, and after that you will see sets of 3. i think it's tough to actually know what the user has seen, since if we do something like "if a link has a been clicked", it will stay that way forever once clicked, and doing something like "if the content has been scrolled into view" is complicated and requires javascript. so this might be the simplest solution for now. lmk what you think.

> Is this the place where we should discuss the max line length for various screens? 

that's #145, i think

> Also, do you know by any chance why (in my screenshots above) the size of the icons in the list is different on firefox vs the other two browsers? The icons look smaller on the other two browsers – this is not a big deal but wondered if you intended that? 

i don't know why and it's not intentional. :/ just a rendering difference that I haven't had time to investigate

**Comment by gissoo** [comment]
> > In the designs it's not centered, just like the other icons it's at the most right edge of the rectangular background.
> 
> oooooops good catch. should be fixed now
> 

- @thatbudakguy Thank you!! Would you please make it full height too? It was full height before, now it's not, sorry.

> > To your point, even though they are always visually right below the clickable list, only one of them is immediately seen below, but there is not an immediate way to know all of which haven't been viewed yet.
> 
> for #150 I've switched it to show the icons for all of the sections except the one you're currently viewing in the icon nav; you can [see the preview of that here](https://startwords-pr-152.onrender.com/issues/1/data-beyond-vision/). the first set of icons shows all of them, and after that you will see sets of 3. i think it's tough to actually know what the user has seen, since if we do something like "if a link has a been clicked", it will stay that way forever once clicked, and doing something like "if the content has been scrolled into view" is complicated and requires javascript. so this might be the simplest solution for now. lmk what you think.
> 

- This is awesome and really smart!! Thank you!! I was having some thoughts that led me to wish we had thought of a "Back to the top button" since this essay is very long – I think the last icon nav would be helpful in that though and could act as the "back to the top" but for RM's article I wish we had that! (maybe a feature to have for the future if it's complicated and late for now?) 
Also, conceptually it would be nice to see all of the icons in the last nav as well (just like the first one), but it's not needed really since the stacking on is right above the last icon nav.

> > Is this the place where we should discuss the max line length for various screens?
> 
> that's #145, i think
> 
> > Also, do you know by any chance why (in my screenshots above) the size of the icons in the list is different on firefox vs the other two browsers? The icons look smaller on the other two browsers – this is not a big deal but wondered if you intended that?
> 
> i don't know why and it's not intentional. :/ just a rendering difference that I haven't had time to investigate

- That's ok! Not important really.

**Comment by thatbudakguy** [comment]
> Would you please make it full height too? It was full height before, now it's not, sorry.

done; you might need to hard refresh to see the change (it took a minute or two for me)

> This is awesome and really smart

I can't take any credit, i think this was @rlskoeser's idea from the beginning!

**Comment by gissoo** [comment]
> > Would you please make it full height too? It was full height before, now it's not, sorry.
> 
> done; you might need to hard refresh to see the change (it took a minute or two for me)
> 

- @thatbudakguy I just viewed it but it looks distorted/resized disproportionately for some reason :( it looks like it's stretched vertically, if it can't be fixed don't spend too much time plz. 
 
> > This is awesome and really smart
> 
> I can't take any credit, i think this was @rlskoeser's idea from the beginning!

- wow ...her 🧠 again :D

**Comment by thatbudakguy** [comment]
> I just viewed it but it looks distorted/resized disproportionately for some reason :( it looks like it's stretched vertically, if it can't be fixed don't spend too much time plz. 

try now*

*in about two minutes

**Comment by gissoo** [comment]
> > I just viewed it but it looks distorted/resized disproportionately for some reason :( it looks like it's stretched vertically, if it can't be fixed don't spend too much time plz.
> 
> try now*
> 
> *in about two minutes

- it looks much better now! Thanks!!
