### ISSUE TITLE
On mobile, clickable area of "Issues" in nav covers most of the "S" homepage link

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#89]
I noticed something about the nav (#60) on mobile. It's very difficult to click the Startwords "S" to get back to the homepage. The clickable area for the "issues" button is so large that it extends over the "S." [Here's a video](https://www.dropbox.com/s/9nyl5iuvq5c15uu/RPReplay_Final1592430603.mov?dl=0) cropped to show the nav as I tap "issues" a few times. You'll see the clickable area flash with each tap, and that its boundaries cover the "S."

Firefox 24.1 / iPhone 6s / iOS 13.3.1

**Comment by thatbudakguy** [comment]
I had been wondering why Firefox on iOS isn't even an entry on any of the tables on [caniuse.com](https://caniuse.com/), which is the go-to source for figuring out why things work in some browsers but not others.

TIL [from wikipedia](https://en.wikipedia.org/wiki/Firefox_for_iOS):
> Apple's policies require all iOS apps that browse the web to use the iOS built-in iOS WebKit-based rendering framework and WebKit JavaScript, so using Gecko wasn't possible.

So, "firefox for iOS" is basically a reskinned Safari, because Apple doesn't allow Mozilla to use its browser engine on Apple devices.

Out of curiousity, @gwijthoff can you duplicate this on Safari on your device as well? I tested on Safari (desktop!) just now and was able to duplicate it, so I think this is a Safari/WebKit thing.

**Comment by gwijthoff** [comment]
@thatbudakguy yup, seems like the same issue occurs on Safari mobile and desktop for me. Good sleuthing!

**Comment by thatbudakguy** [comment]
@gwijthoff OK, I've added a very basic fix for this - on safari the interactive area still doesn't _exactly_ correspond to the shapes like it does on other browsers, but I think the correspondence is enough that you won't be getting unpredictable results when tapping. go ahead and try it out.

**Comment by gwijthoff** [comment]
That fixed it! Thanks so much @thatbudakguy
