### ISSUE TITLE
Scrolling through long text in contextual notes closes the note on iOS

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#90]
Tested this on an iPhone and iPad. [Here's a video.](https://www.dropbox.com/s/on2f9szeuxxif41/RPReplay_Final1592433497.MP4?dl=0) Scrolling *up* to the top of the text in a long contextual note works fine, but scrolling *down* on the long contextual note text inadvertently closes the note.

**Comment by thatbudakguy** [comment]
I think this might be a use case for the exact scroll-overflow thing you found, @rlskoeser!

**Comment by rlskoeser** [comment]
@gwijthoff made some slight style adjustments, would you check if it helps any?

**Comment by gwijthoff** [comment]
That fixed the scroll issue! But for some reason the "X" icon for closing the note won't appear for me on contextual note No. 5 *only!* This bug won't die.

![IMG_5879](https://user-images.githubusercontent.com/5580840/85058318-ec2bc880-b16f-11ea-95f4-7d663ff4b91f.PNG)

**Comment by rlskoeser** [comment]
Wow, this is wild. The only browser/device I can currently duplicate it on is my iPad; when I connect it to my laptop and debug with Safari, the element is positioned _right where it's supposed to be_ and I can't figure out what style is making it invisible, or why it isn't impacting any of the other notes.

@thatbudakguy any ideas?

**Comment by thatbudakguy** [comment]
it looks like this is because the footnote backref link is _inside_ the paragraph of text that comprises the footnote:
```html
<p>
  footnote text...
  <a class="footnote-backref">↩︎</a>
</p>
```
because we have `overflow` set on the paragraph in css, the backlink is culled for being "outside" its parent the paragraph, even though it's absolutely positioned. you can remove `overflow-y: scroll` on the paragraph to see it appear. it will only be hidden if the text of the paragraph is long enough to cause a scrollbar in the element (this happens at least for notes 3, 4, and 5 for me).

[this post](https://front-back.com/how-to-make-absolute-positioned-elements-overlap-their-overflow-hidden-parent/) details one strategy for mitigating the issue (put the backlink inside another element so the `<p>` is no longer its parent); we could also just move the backlink out of the paragraph to be its sibling. I don't know what generates the footnote HTML though, so we might not be able to do either of those things.

I tried setting `overflow-y: scroll` on the whole footnote container instead of the just the paragraph, which yielded...interesting results, but isn't something I think we want to do. Ultimately I think we're in a tough spot here trying to take HTML generated for one purpose (endnotes) and bend it to several different presentation styles in different situations.

**Comment by rlskoeser** [comment]
Ok, came up with a possible workaround based on @thatbudakguy 's research and my own experience that the backref link is clickable even though it isn't visible. @gwijthoff please test and see if this works for you.

**Comment by gwijthoff** [comment]
@rlskoeser [Still getting that behavior](https://www.dropbox.com/s/yb0f07ejc7zipt9/RPReplay_Final1593031327.MP4?dl=0) — scrolling down in the text of a long note closes the note. Am I looking at the wrong thing?

**Comment by rlskoeser** [comment]
I thought I fixed that! It's back again?

**Comment by rlskoeser** [comment]
@gwijthoff I tested on my iPad with Safari & Firefox and I can't duplicate (although I see a different problem with my workaround for the missing close button happening in one of them, will fix...)

**Comment by rlskoeser** [comment]
Hmm, ok — it's now happening for me on the iPad with Firefox but _not_ with Safari. @gwijthoff what browser are you testing with on mobile? 

However, I see from your video that the close icon is displaying on note 5! Can you tap it to close the note?

**Comment by gwijthoff** [comment]
@rlskoeser I'm using Firefox v. 26.0 (18099). Clicking the X in note 5 does close the note. But that weird scroll behavior remains.

**Comment by gissoo** [comment]
@rlskoeser I'm also noticing this (scrolling the text inside the note closes the note) on iOS FF/same version as Grant's. Also, it's interesting that if I scroll down a note and close it, and reopen it the scroll is still at the bottom/doesn't reset.

**Comment by rlskoeser** [comment]
@thatbudakguy I added ` -webkit-overflow-scrolling: touch;` to the contextual note `li` element and it fixed the problem on iOS Safari but not on iOS FF. It's a non-standard style; I'm not sure what our options are for FF. I also added `overscroll-behavior: none;` which seemed to help the note scrolling behavior in some browsers. (Looks like `overscroll-behavior: contain;` is also an option, I'm not sure if that would make any difference.)

**Comment by thatbudakguy** [comment]
I added `overscroll-behavior: none;` to the `<p>` element _inside_ the note `<li>`, which seems to be working on Firefox. For Safari, I don't think we really have an option except for waiting for them to implement `overscroll-behavior`...the workaround [described here](https://dev.to/mpuckett/the-holy-grail-web-app-shell-with-header-and-footer-for-iphone-549j) is super gnarly, and doesn't really match our particular case anyway.

@gissoo @gwijthoff could I get a final Y/N verdict on this? it may stay broken on Safari for awhile, but when they add support for `overscroll-behavior` it will magically start working, so I think our best bet may be to just wait.

**Comment by gissoo** [comment]
@thatbudakguy thanks for writing. Is it supposed to be broken on Safari now? 
This is weird, because at the time it is working for me on iOS Safari and Chrome but not on iOS Firefox (all of my browsers are up-to-date).

**Comment by gwijthoff** [comment]
@thatbudakguy thanks for continuing to plug away at this! Oddly enough, contextual note scrolling now works for me on iPhone and iPad Safari, but is broken on both iPhone and iPad Firefox. [Here's a video.](https://www.dropbox.com/s/ieoku3i0xkdd86m/RPReplay_Final1594237193.MP4?dl=0)

**Comment by thatbudakguy** [comment]
Super interesting to hear that it's broken on iOS FF, but I think I can guess why: WebKit (the engine) hasn't implemented support for `overscroll-behavior`, which means iOS FF hasn't, but Safari's fork of WebKit has.

I think this and the other issue (#66) that apply to iOS FF only should be closed, for two reasons:
- they both depend on a property being implemented, which it should eventually be
- iOS FF has such a tiny market share (less than half of one percent) that most browser comparison sites like caniuse.com don't even bother listing it.

FWIW everything I'm seeing suggests it _should_ be broken on Safari too, but glad to hear it's not!

**Comment by rlskoeser** [comment]
@thatbudakguy thanks for all the testing and review on this! Glad to hear that iOS FF can be treated as an edge case, and that behavior should eventually improve. FWIW, the behavior in iOS Safari seemed to be fixed by the non-standard property I added, which I noted here https://github.com/Princeton-CDH/startwords/issues/90#issuecomment-654303244

**Comment by gissoo** [comment]
Thank you all for writing!! I agree! Let's close.

**Comment by gwijthoff** [comment]
Not to belabor this issue (agree that it should be closed), but I just discovered that on Firefox Focus (their privacy browser), the scrolling *does* work in long notes! 🤷‍♂️

**Comment by thatbudakguy** [comment]
I _think_ this is because focus uses `UIWebView`s instead of webkit directly...been down this road before myself when I was confused why Focus was loading stuff differently than my desktop Firefox. Fun times! Gotta love that Apple forces so many developers to use their platform in very particular ways, but all respect to the Mozilla folks for finding workarounds.
